# FRAME-AD: Foundation Model for Robust and Adaptive Multimodal Evaluation in Alzheimer's Disease

**Author:** Akua Osei — PhD Student, University of Texas Rio Grande Valley  
**Task:** 3-Class Classification (CN vs MCI vs AD)  
**Dataset:** ADNI (`ADNI_data_26.csv`)  
**Primary Model:** FRAME-AD (TabPFN 3.5)  
**Comparison Models:** TabPFN 3.0, TabPFN v2.5, XGBoost, LightGBM, CatBoost, Random Forest, Logistic Regression, TabNet, RealMLP, AutoGluon, MITRA  

---

## Experiments
| # | Experiment | Description |
|---|-----------|-------------|
| E1 | Benchmarking | FRAME-AD (TabPFN 3.5) vs 11 baseline methods across two groups |
| E2 | Multimodal Ablation | Performance across modality combinations using FRAME-AD (TabPFN 3.5) |
| E3 | Data Efficiency | AUC at 10%, 25%, 50%, 75%, 100% training data |
| E4 | Calibration Analysis | Brier scores + reliability diagrams |
| E5 | SHAP Disease Insights | Global + APOE4 + Sex subgroup interpretability using FRAME-AD (TabPFN 3.5) |

---

## Setup Before Running
```bash
pip install tabpfn-client>=0.6.0 xgboost lightgbm catboost pytabkit shap scikit-learn matplotlib seaborn pandas numpy
huggingface-cli login   # paste your HuggingFace token
```
Accept TabPFN license at: https://huggingface.co/Prior-Labs/tabpfn_3

In [ ]:
# Uninstall existing xgboost to ensure a clean slate
!pip uninstall -y xgboost

# Attempt to install a pre-built CPU-only wheel for xgboost.
# The environment variable `XGBOOST_BUILD_WITH_CUDA=0` serves as a hint for pip
# to prefer CPU wheels if available. The `--no-cache-dir` ensures a fresh download.
# We no longer use `--no-binary :all:` to avoid source build failures.
!XGBOOST_BUILD_WITH_CUDA=0 pip install --no-cache-dir xgboost==1.7.6

# Keep other necessary installations
!pip install lightgbm shap scikit-learn matplotlib seaborn pandas numpy

Found existing installation: xgboost 3.4.1
Uninstalling xgboost-3.4.1:
  Successfully uninstalled xgboost-3.4.1
Collecting xgboost==1.7.6
  Downloading xgboost-1.7.6-py3-none-manylinux2014_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost==1.7.6) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost==1.7.6) (1.16.3)
Downloading xgboost-1.7.6-py3-none-manylinux2014_x86_64.whl (200.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.3/200.3 MB 163.9 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-1.7.6
Requirement already satisfied: lightgbm in /usr/local/lib/python3.13/dist-packages (4.6.0)
Requirement already satisfied: shap in /usr/local/lib/python3.13/dist-packages (0.52.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.13/dist-packages (0.13.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from lightgbm) (1.16.3)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.13/dist-packages (from shap) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.13/dist-packages (from shap) (26.3)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.13/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.13/dist-packages (from shap) (0.61.2)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.13/dist-packages (from shap) (0.44.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.13/dist-packages (from shap) (3.1.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [ ]:
!pip install torch pytorch-tabnet

Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (2.11.0+cpu)
Collecting pytorch-tabnet
  Downloading pytorch_tabnet-4.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch) (2025.12.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from pytorch-tabnet) (2.1.3)
Requirement already satisfied: scikit_learn>0.21 in /usr/local/lib/python3.13/dist-packages (from pytorch-tabnet) (1.6.1)
Requirement already satisfied: scipy>1.4 in /usr/local/lib/python3.13/dist-packages (from pytorch-tabnet) (1.16.3)
Requirement already satisfied: tqdm>=4.36 in /usr/local/lib/python3.13/dist-packages (from pytorch-tabnet) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit_learn>0.21->pytorch-tabnet) (3.1.2)
Downloading pytorch_tabnet-4.1.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.5/44.5 kB 1.0 MB/s eta 0:00:00
Installing collected packages: pytorch-tabnet
Successfully installed pytorch-tabnet-4.1.0

In [ ]:
!pip install autogluon.tabular

Collecting autogluon.tabular
  Downloading autogluon_tabular-1.6.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: numpy<2.6.0,>=1.25.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (2.1.3)
Requirement already satisfied: scipy<1.19,>=1.5.4 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (1.16.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (2.2.3)
Requirement already satisfied: scikit-learn<1.10.0,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular) (3.6.1)
Collecting autogluon.core==1.6.3 (from autogluon.tabular)
  Downloading autogluon_core-1.6.3-py3-none-any.whl.metadata (14 kB)
Collecting autogluon.features==1.6.3 (from autogluon.tabular)
  Downloading autogluon_features-1.6.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular) (2.32.4)
Requirement already satisfied: matplotlib<3.12,>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.6.3->autogluon.tabular)
  Downloading boto3-1.43.100-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: typing-extensions<5,>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular) (4.16.0)
Collecting autogluon.common==1.6.3 (from autogluon.core==1.6.3->autogluon.tabular)
  Downloading autogluon_common-1.6.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pyarrow<25.0.0,>=23.0.1 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular) (23.0.1)
Requirement already satisfied: psutil<7.3.0,>=5.7.3 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular) (5.9.5)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular) (1.6.0)
Requirement already satisfied: pyyaml>=5.4 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular) (6.0.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular) (26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2026.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<1.10.0,>=1.4.0->autogluon.tabular) (3.6.0)
Collecting botocore<1.44.0,>=1.43.100 (from boto3<2,>=1.10->autogluon.core==1.6.3->autogluon.tabular)
  Downloading botocore-1.43.100-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.6.3->autogluon.tabular)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2,>=1.10->autogluon.core==1.6.3->autogluon.tabular)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib<1.7,>=1.2->autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=2.0.0->autogluon.tabular) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular) (2026.7.22)
Downloading autogluon_tabular-1.6.3-py3-none-any.whl (514 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 514.8/514.8 kB 5.5 MB/s eta 0:00:00
Downloading autogluon_core-1.6.3-py3-none-any.whl (248 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.4/248.4 kB 16.1 MB/s eta 0:00:00
Downloading autogluon_features-1.6.3-py3-none-any.whl (112 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.3/112.3 kB 8.6 MB/s eta 0:00:00
Downloading autogluon_common-1.6.3-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.7/90.7 kB 6.8 MB/s eta 0:00:00
Downloading boto3-1.43.100-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 10.6 MB/s eta 0:00:00
Downloading botocore-1.43.100-py3-none-any.whl (15.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 87.6 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 8.0 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3, autogluon.common, autogluon.features, autogluon.core, autogluon.tabular
Successfully installed autogluon.common-1.6.3 autogluon.core-1.6.3 autogluon.features-1.6.3 autogluon.tabular-1.6.3 boto3-1.43.100 botocore-1.43.100 jmespath-1.1.0 s3transfer-0.19.2

In [ ]:
# Install CatBoost for AutoGluon's presets
!pip install autogluon.tabular[catboost]

Requirement already satisfied: autogluon.tabular[catboost] in /usr/local/lib/python3.13/dist-packages (1.6.3)
Requirement already satisfied: numpy<2.6.0,>=1.25.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular[catboost]) (2.1.3)
Requirement already satisfied: scipy<1.19,>=1.5.4 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular[catboost]) (1.16.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular[catboost]) (2.2.3)
Requirement already satisfied: scikit-learn<1.10.0,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular[catboost]) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular[catboost]) (3.6.1)
Requirement already satisfied: autogluon.core==1.6.3 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular[catboost]) (1.6.3)
Requirement already satisfied: autogluon.features==1.6.3 in /usr/local/lib/python3.13/dist-packages (from autogluon.tabular[catboost]) (1.6.3)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[catboost])
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular[catboost]) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular[catboost]) (2.32.4)
Requirement already satisfied: matplotlib<3.12,>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular[catboost]) (3.10.0)
Requirement already satisfied: boto3<2,>=1.10 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular[catboost]) (1.43.100)
Requirement already satisfied: typing-extensions<5,>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular[catboost]) (4.16.0)
Requirement already satisfied: autogluon.common==1.6.3 in /usr/local/lib/python3.13/dist-packages (from autogluon.core==1.6.3->autogluon.tabular[catboost]) (1.6.3)
Requirement already satisfied: pyarrow<25.0.0,>=23.0.1 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular[catboost]) (23.0.1)
Requirement already satisfied: psutil<7.3.0,>=5.7.3 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular[catboost]) (5.9.5)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular[catboost]) (1.6.0)
Requirement already satisfied: pyyaml>=5.4 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular[catboost]) (6.0.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular[catboost]) (26.3)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost]) (0.21)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost]) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost<1.3,>=1.2->autogluon.tabular[catboost]) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular[catboost]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular[catboost]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular[catboost]) (2026.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<1.10.0,>=1.4.0->autogluon.tabular[catboost]) (3.6.0)
Requirement already satisfied: botocore<1.44.0,>=1.43.100 in /usr/local/lib/python3.13/dist-packages (from boto3<2,>=1.10->autogluon.core==1.6.3->autogluon.tabular[catboost]) (1.43.100)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.13/dist-packages (from boto3<2,>=1.10->autogluon.core==1.6.3->autogluon.tabular[catboost]) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from boto3<2,>=1.10->autogluon.core==1.6.3->autogluon.tabular[catboost]) (0.19.2)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib<1.7,>=1.2->autogluon.common==1.6.3->autogluon.core==1.6.3->autogluon.tabular[catboost]) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular[catboost]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular[catboost]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular[catboost]) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular[catboost]) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular[catboost]) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<3.12,>=3.7.0->autogluon.core==1.6.3->autogluon.tabular[catboost]) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost<1.3,>=1.2->autogluon.tabular[catboost]) (9.1.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular[catboost]) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular[catboost]) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular[catboost]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->autogluon.core==1.6.3->autogluon.tabular[catboost]) (2026.7.22)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 26.6 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [ ]:

%pip install -q --upgrade tabpfn-client==0.6.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.4/109.4 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.3/472.3 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 31.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.6/220.6 kB 18.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.2/53.2 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.7/803.7 kB 38.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 96.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [ ]:
from getpass import getpass
from tabpfn_client import set_access_token

API_TOKEN = getpass("Paste your Prior Labs API key: ")
set_access_token(API_TOKEN)

print("Prior Labs API token saved for this session.")

Paste your Prior Labs API key: ··········
Prior Labs API token saved for this session.

In [ ]:
!pip install -q catboost
!pip install -q pytabkit
!pip install -q -U "autogluon.tabular[catboost]>=1.4.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.0/364.0 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 853.0/853.0 kB 18.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 40.2 MB/s eta 0:00:00

In [ ]:
import importlib.metadata
import numpy as np
import pandas as pd
import sklearn

print("tabpfn-client:", importlib.metadata.version("tabpfn-client"))
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)

from tabpfn_client import TabPFNClassifier

print("TabPFN client imported successfully.")

tabpfn-client: 0.6.0
NumPy: 2.1.3
Pandas: 2.2.3
Scikit-learn: 1.6.1
TabPFN client imported successfully.

##  Imports

In [ ]:
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

DATA_PATH   = "ADNI_data_26.csv"
OUTPUT_DIR  = "frame_ad_results"
RANDOM_SEED = 42
CV_FOLDS    = 5
TEST_SIZE   = 0.20
N_JOBS      = -1

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(f"{OUTPUT_DIR}/figures", exist_ok=True)

import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
import torch

from sklearn.metrics import (
    roc_auc_score, accuracy_score, f1_score,
    matthews_corrcoef, brier_score_loss,
    balanced_accuracy_score, log_loss,
    confusion_matrix, classification_report,
    precision_recall_fscore_support
)
from sklearn.preprocessing import label_binarize
from sklearn.impute import SimpleImputer
from sklearn.model_selection import StratifiedKFold, train_test_split

torch.set_default_device('cpu')
torch.manual_seed(RANDOM_SEED)

# Define CLASS_LABELS for multi-class classification
CLASS_LABELS = [0, 1, 2]  # Corresponding to CN, MCI, AD numerical labels

print(" Configuration and Imports Updated")

 Configuration and Imports Updated

##  Configuration

In [ ]:
# ── Edit these paths/settings as needed ──────────────────────
DATA_PATH   = "ADNI_data_26.csv"   # path to your ADNI merged CSV
OUTPUT_DIR  = "frame_ad_results"     # folder where results will be saved
RANDOM_SEED = 42
CV_FOLDS    = 5
TEST_SIZE   = 0.20
N_JOBS      = -1                     # -1 = use all CPU cores

# Create output directories
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(f"{OUTPUT_DIR}/figures", exist_ok=True)

print(f" Configuration set")
print(f"   Data path  : {DATA_PATH}")
print(f"   Output dir : {OUTPUT_DIR}")
print(f"   CV folds   : {CV_FOLDS}")
print(f"   Test size  : {TEST_SIZE*100:.0f}%")
print(f"   Random seed: {RANDOM_SEED}")

 Configuration set
   Data path  : ADNI_data_26.csv
   Output dir : frame_ad_results
   CV folds   : 5
   Test size  : 20%
   Random seed: 42

## Feature Definitions

In [ ]:
# ── Feature groups by modality ────────────────────────────────
COGNITIVE = [
    'ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL',
    'MMSE_MMSCORE',  'MOCA_MOCA'
]

DEMOGRAPHICS = ['PTDEMOG_PTGENDER', 'PTDEMOG_PTEDUCAT','AGE']

APOE = ['APOERES_?4 Count']

CSF = ['UPENNBIOMK_ABETA42', 'UPENNBIOMK_TAU', 'UPENNBIOMK_PTAU']

MRI = [
    'UCSFFSX7_ST29SV',   # Left Hippocampus
    'UCSFFSX7_ST30SV',   # Right Hippocampus
    'UCSFFSX7_ST11SV',   # Left Entorhinal Cortex
    'UCSFFSX7_ST12SV',   # Right Entorhinal Cortex
    'UCSFFSX7_ST1SV',    # Intracranial Volume (ICV)
    'UCSFFSX7_ST16SV',   # Left Lateral Ventricle
    'UCSFFSX7_ST17SV',   # Right Lateral Ventricle
]

AMYLOID = [
    'AMYLOID_SUMMARY_SUVR',
    'AMYLOID_CENTILOIDS',
    'AMYLOID_COMPOSITE_REF_SUVR',
    'AMYLOID_HIPPOCAMPUS_SUVR',
    'AMYLOID_CTX_ENTORHINAL_SUVR',
    'AMYLOID_CTX_PRECUNEUS_SUVR',
    'AMYLOID_CTX_POSTERIORCINGULATE_SUVR'
]

ALL_FEATURES = COGNITIVE + DEMOGRAPHICS + APOE + CSF + MRI + AMYLOID

# ── Modality combinations for Experiment 2 (Ablation) ─────────
MODALITY_COMBOS = {
    'Cognitive only':              COGNITIVE,
    'Demographics + Genetics':     DEMOGRAPHICS + APOE,
    'CSF only':                    CSF,
    'MRI only':                    MRI,
    'Amyloid PET only':            AMYLOID,
    'Cognitive + Demo + Genetics': COGNITIVE + DEMOGRAPHICS + APOE,
    'Cognitive + MRI':             COGNITIVE + MRI,
    'Cognitive + PET':             COGNITIVE + AMYLOID,
    'Cognitive + CSF':             COGNITIVE + CSF,
    'All modalities (FULL)':       ALL_FEATURES,
}

# ── Human-readable feature labels for SHAP plots ──────────────
FEATURE_LABELS = {
    'ADAS_TOTSCORE':    'ADAS-Cog 11',
    'ADAS_TOTAL13':     'ADAS-Cog 13',
    'FAQ_FAQTOTAL':     'FAQ',
    'MMSE_MMSCORE':     'MMSE',
    'MOCA_MOCA':        'MoCA',
    'PTDEMOG_PTGENDER': 'Sex',
    'PTDEMOG_PTEDUCAT': 'Education',
    'Age':              'Age',
    'APOERES_?4 Count': 'APOE ε4 count',
    'UPENNBIOMK_ABETA42': 'CSF Aβ42',
    'UPENNBIOMK_TAU':   'CSF Total-tau',
    'UPENNBIOMK_PTAU':  'CSF p-tau 181',
    'UCSFFSX7_ST29SV':  'Hippocampus L',
    'UCSFFSX7_ST30SV':  'Hippocampus R',
    'UCSFFSX7_ST11SV':  'Entorhinal L',
    'UCSFFSX7_ST12SV':  'Entorhinal R',
    'UCSFFSX7_ST1SV':   'ICV',
    'UCSFFSX7_ST16SV':  'Lat. Ventricle L',
    'UCSFFSX7_ST17SV':  'Lat. Ventricle R',
    'AMYLOID_SUMMARY_SUVR':               'Amyloid Global SUVR',
    'AMYLOID_CENTILOIDS':                 'Centiloids',
    'AMYLOID_COMPOSITE_REF_SUVR':         'Composite SUVR',
    'AMYLOID_HIPPOCAMPUS_SUVR':           'Amyloid Hippocampus',
    'AMYLOID_CTX_ENTORHINAL_SUVR':        'Amyloid Entorhinal',
    'AMYLOID_CTX_PRECUNEUS_SUVR':         'Amyloid Precuneus',
    'AMYLOID_CTX_POSTERIORCINGULATE_SUVR':'Amyloid Post. Cingulate',
}

print(f"Feature definitions loaded")
print(f"   Total features  : {len(ALL_FEATURES)}")
print(f"   Cognitive       : {len(COGNITIVE)}")
print(f"   Demographics    : {len(DEMOGRAPHICS)}")
print(f"   Genetics (APOE) : {len(APOE)}")
print(f"   CSF biomarkers  : {len(CSF)}")
print(f"   MRI (FreeSurfer): {len(MRI)}")
print(f"   Amyloid PET     : {len(AMYLOID)}")
print(f"   Ablation combos : {len(MODALITY_COMBOS)}")

Feature definitions loaded
   Total features  : 26
   Cognitive       : 5
   Demographics    : 3
   Genetics (APOE) : 1
   CSF biomarkers  : 3
   MRI (FreeSurfer): 7
   Amyloid PET     : 7
   Ablation combos : 10

## Helper Functions

In [ ]:
def compute_ece(y_true, y_proba, n_bins=10):
    bin_boundaries = np.linspace(0, 1, n_bins + 1)
    bin_lowers = bin_boundaries[:-1]
    bin_uppers = bin_boundaries[1:]
    confidences = np.max(y_proba, axis=1)
    predictions = np.argmax(y_proba, axis=1)
    accuracies = (predictions == y_true)
    ece = 0
    for bin_lower, bin_upper in zip(bin_lowers, bin_uppers):
        in_bin = (confidences > bin_lower) & (confidences <= bin_upper)
        prop_in_bin = np.mean(in_bin)
        if prop_in_bin > 0:
            accuracy_in_bin = np.mean(accuracies[in_bin])
            avg_confidence_in_bin = np.mean(confidences[in_bin])
            ece += np.abs(avg_confidence_in_bin - accuracy_in_bin) * prop_in_bin
    return ece

def compute_metrics(y_true, y_pred, y_proba, classes=[0, 1, 2]):
    y_true = np.array(y_true)
    y_bin = label_binarize(y_true, classes=classes)
    acc = accuracy_score(y_true, y_pred)
    bacc = balanced_accuracy_score(y_true, y_pred)
    f1_macro = f1_score(y_true, y_pred, average='macro', zero_division=0)
    mcc = matthews_corrcoef(y_true, y_pred)
    loss = log_loss(y_true, y_proba, labels=classes)
    ece = compute_ece(y_true, y_proba)
    try:
        # Ensure we use average='macro' and multi_class='ovr'
        auc_macro = roc_auc_score(y_true, y_proba, multi_class='ovr', average='macro', labels=classes)
    except:
        auc_macro = np.nan

    brier_avg = np.mean([brier_score_loss(y_bin[:, i], y_proba[:, i]) for i in range(len(classes))])
    cm = confusion_matrix(y_true, y_pred, labels=classes)

    specs = []
    for i in range(len(classes)):
        tn = np.sum(cm) - (np.sum(cm[i, :]) + np.sum(cm[:, i]) - cm[i, i])
        fp = np.sum(cm[:, i]) - cm[i, i]
        specs.append(tn / (tn + fp) if (tn + fp) > 0 else 0)

    res = {
        'Accuracy': acc,
        'Balanced_Acc': bacc,
        'F1_Macro': f1_macro,
        'AUC_Macro': auc_macro,
        'MCC': mcc,
        'LogLoss': loss,
        'Brier': brier_avg,
        'ECE': ece
    }

    p, r, f, _ = precision_recall_fscore_support(y_true, y_pred, labels=classes, zero_division=0)
    for i, cname in enumerate(['CN', 'MCI', 'AD']):
        res[f'{cname}_Prec'] = p[i]
        res[f'{cname}_Rec'] = r[i]
        res[f'{cname}_Spec'] = specs[i]
        res[f'{cname}_F1'] = f[i]

    res['ConfusionMatrix'] = cm
    return res

# Verification test
test_y_true = [0, 1, 2, 0]
test_y_pred = [0, 1, 2, 1]
test_y_proba = np.array([[0.8, 0.1, 0.1], [0.2, 0.7, 0.1], [0.1, 0.2, 0.7], [0.3, 0.6, 0.1]])
test_metrics = compute_metrics(test_y_true, test_y_pred, test_y_proba)
print("Verification - Metrics Keys:", list(test_metrics.keys()))
if 'AUC_Macro' in test_metrics:
    print(" Success: 'AUC_Macro' key found.")
else:
    print(" Error: 'AUC_Macro' key missing.")

def median_impute(X_train, X_test):
    imp = SimpleImputer(strategy='median')
    Xtr_i = pd.DataFrame(imp.fit_transform(X_train), columns=X_train.columns)
    Xte_i = pd.DataFrame(imp.transform(X_test), columns=X_test.columns)
    return Xtr_i, Xte_i

def align_probabilities(raw_proba, model_classes, target_classes=[0, 1, 2]):
    aligned = np.zeros((len(raw_proba), len(target_classes)))
    for i, cls in enumerate(model_classes):
        if cls in target_classes:
            aligned[:, target_classes.index(cls)] = raw_proba[:, i]
    row_sums = aligned.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1.0
    return aligned / row_sums

def get_tabpfn():
    from tabpfn_client import TabPFNClassifier
    from tabpfn_client.constants import ModelVersion
    return TabPFNClassifier.create_default_for_version(
        ModelVersion.V3_5,
        ignore_pretraining_limits=True
    )

skf = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_SEED)
print(" Unified Metrics and Helpers Updated")

Verification - Metrics Keys: ['Accuracy', 'Balanced_Acc', 'F1_Macro', 'AUC_Macro', 'MCC', 'LogLoss', 'Brier', 'ECE', 'CN_Prec', 'CN_Rec', 'CN_Spec', 'CN_F1', 'MCI_Prec', 'MCI_Rec', 'MCI_Spec', 'MCI_F1', 'AD_Prec', 'AD_Rec', 'AD_Spec', 'AD_F1', 'ConfusionMatrix']
 Success: 'AUC_Macro' key found.
 Unified Metrics and Helpers Updated

In [ ]:
print(" All new classifiers imported. Helper functions were already defined in the previous cell.")

 All new classifiers imported. Helper functions were already defined in the previous cell.

##  Data Loading & Cohort Preparation

In [ ]:
# Load raw CSV
df = pd.read_csv(DATA_PATH)
print(f"Raw dataset shape: {df.shape}")

# Filter to valid diagnosis labels
task1 = df[df['DX_DX_GROUP'].isin(['CN', 'MCI', 'AD'])].copy()
task1['label'] = task1['DX_DX_GROUP'].map({'CN': 0, 'MCI': 1, 'AD': 2})

# Extract feature matrix — keep only features available in the data
available_features = [f for f in ALL_FEATURES if f in task1.columns]
X = task1[available_features].copy()
y = task1['label'].copy()

# Convert all features to numeric (coerce non-numeric to NaN)
for col in X.columns:
    X[col] = pd.to_numeric(X[col], errors='coerce')

# Reset indices for clean alignment
X = X.reset_index(drop=True)
y = y.reset_index(drop=True)

print(f"\n Cohort prepared")
print(f"   Total subjects  : {len(X)}")
print(f"   CN              : {(y==0).sum()}")
print(f"   MCI             : {(y==1).sum()}")
print(f"   AD              : {(y==2).sum()}")
print(f"   Features loaded : {X.shape[1]} / {len(ALL_FEATURES)}")
print(f"\nMissingness by category:")
cats = {
    'Cognitive':    COGNITIVE,
    'Demographics': DEMOGRAPHICS,
    'Genetics':     APOE,
    'CSF':          CSF,
    'MRI':          MRI,
    'Amyloid PET':  AMYLOID,
}
for cat, feats in cats.items():
    avail = [f for f in feats if f in X.columns]
    pct   = X[avail].isnull().mean().mean() * 100
    print(f"   {cat:<15}: {pct:.1f}% missing")

Raw dataset shape: (3700, 669)

 Cohort prepared
   Total subjects  : 3700
   CN              : 1493
   MCI             : 1206
   AD              : 1001
   Features loaded : 26 / 26

Missingness by category:
   Cognitive      : 25.6% missing
   Demographics   : 0.8% missing
   Genetics       : 22.4% missing
   CSF            : 55.4% missing
   MRI            : 16.5% missing
   Amyloid PET    : 41.8% missing

## Train / Test Split

In [ ]:
# Fixed 80/20 stratified split used for E3, E4, E5
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=TEST_SIZE,
    stratify=y,
    random_state=RANDOM_SEED
)

# Initialize and fit the imputer on the ADNI training data
# This imputer will be used for ADNI median-imputed baselines (Group 1)
imputer = SimpleImputer(strategy='median')
imputer.fit(X_train)

# Store feature column names, needed for creating imputed DataFrames
feature_cols = X_train.columns

print(f" Train/test split complete")
print(f"   Train : {len(X_train)} subjects "
      f"(CN={( y_train==0).sum()}  MCI={(y_train==1).sum()}  AD={(y_train==2).sum()})")
print(f"   Test  : {len(X_test)} subjects "
      f"(CN={(y_test==0).sum()}  MCI={(y_test==1).sum()}  AD={(y_test==2).sum()})")

 Train/test split complete
   Train : 2960 subjects (CN=1194  MCI=965  AD=801)
   Test  : 740 subjects (CN=299  MCI=241  AD=200)

## Experiment 1: Benchmarking
Compare FRAME-AD (TabPFN 3.5) against 11 methods using stratified 5-fold cross-validation across two groups.

**Group 1 — Median-Imputed Baselines** (missing values filled with feature medians before training):
- Logistic Regression, Random Forest, XGBoost, LightGBM, CatBoost, TabNet, RealMLP

**Group 2 — Native Missing Value Handlers** (no imputation; models handle missingness directly):
- TabPFN v2.5, TabPFN 3.0, TabPFN 3.5 (FRAME-AD), AutoGluon, MITRA

All Group 2 models receive raw data with missing values intact. TabPFN 3.5 is the primary FRAME-AD model. TabPFN v2.5 and 3.0 are included as within-family version comparisons.

In [ ]:
import os
import gc
import traceback
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder, label_binarize
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    roc_auc_score, accuracy_score, f1_score,
    matthews_corrcoef, brier_score_loss, log_loss,
    confusion_matrix, precision_recall_fscore_support
)

warnings.filterwarnings("ignore")

RANDOM_SEED = 42
CV_FOLDS = 5
N_JOBS = -1
OUTPUT_DIR = "ADNI results"

os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(f"{OUTPUT_DIR}/figures", exist_ok=True)

def save_model_results(model_name, fold_results, filename):
    df_folds = pd.DataFrame(fold_results)
    numeric_df = df_folds.select_dtypes(include=[np.number])

    summary = pd.DataFrame({
        "Metric": numeric_df.columns,
        "Mean": numeric_df.mean().values,
        "Standard Deviation": numeric_df.std(ddof=1).values
    })
    filepath = os.path.join(OUTPUT_DIR, filename)
    summary.to_csv(filepath, index=False)
    return summary

def display_model_execution_summary(model_name, results, X_data):
    df = pd.DataFrame(results)
    print(f"\n{'='*20} {model_name} EVALUATION {'='*20}")

    # Use standardized metric keys
    main_metrics = ['AUC_Macro', 'Accuracy', 'F1_Macro', 'MCC', 'Brier', 'LogLoss']
    available = [m for m in main_metrics if m in df.columns]
    display(df[available].mean().to_frame('Mean Value'))

    fig, ax = plt.subplots(1, 2, figsize=(15, 5))
    agg_cm = np.sum(np.stack(df['ConfusionMatrix'].values), axis=0)
    sns.heatmap(agg_cm, annot=True, fmt='g', cmap='Blues',
                xticklabels=['CN','MCI','AD'], yticklabels=['CN','MCI','AD'], ax=ax[0])
    ax[0].set_title(f'Aggregated Confusion Matrix: {model_name}')

    corr = X_data.corr()
    sns.heatmap(corr, cmap='RdBu_r', center=0, ax=ax[1])
    ax[1].set_title(f'Feature Correlation Matrix')
    plt.tight_layout()
    plt.show()

print("\n Helper functions standardized to use AUC_Macro.")

 Helper functions standardized to use AUC_Macro.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

print("=" * 60)
print("LOGISTIC REGRESSION")
print("=" * 60)
logistic_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]
    Xtr_i, Xte_i = median_impute(Xtr, Xte)

    model = LogisticRegression(max_iter=5000, random_state=RANDOM_SEED, class_weight='balanced')
    model.fit(Xtr_i, ytr)

    pred = model.predict(Xte_i)
    raw_proba = model.predict_proba(Xte_i)
    proba = align_probabilities(raw_proba, model.classes_)

    m = compute_metrics(yte, pred, proba)
    logistic_results.append(m)
    # Changed 'AUC_Macro' to 'AUC_Macro' to match the compute_metrics return key
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

display_model_execution_summary("Logistic Regression", logistic_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))
save_model_results("Logistic Regression", logistic_results, "logistic_regression_results.csv")

============================================================
LOGISTIC REGRESSION
============================================================
Fold 1: AUC=0.8605, LogLoss=0.6514
Fold 2: AUC=0.8776, LogLoss=0.5878
Fold 3: AUC=0.8598, LogLoss=0.6356
Fold 4: AUC=0.8497, LogLoss=0.6494
Fold 5: AUC=0.8690, LogLoss=0.6230

==================== Logistic Regression EVALUATION ====================

           Mean Value
AUC_Macro    0.863312
Accuracy     0.683784
F1_Macro     0.695927
MCC          0.523879
Brier        0.131011
LogLoss      0.629442

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.75      0.68      0.71       299
         MCI       0.55      0.61      0.58       241
          AD       0.84      0.84      0.84       200

    accuracy                           0.70       740
   macro avg       0.72      0.71      0.71       740
weighted avg       0.71      0.70      0.71       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.683784            0.016878
1   Balanced_Acc  0.695078            0.015810
2       F1_Macro  0.695927            0.017309
3      AUC_Macro  0.863312            0.010510
4            MCC  0.523879            0.024689
5        LogLoss  0.629442            0.025955
6          Brier  0.131011            0.005232
7            ECE  0.033635            0.014037
8        CN_Prec  0.737924            0.009468
9         CN_Rec  0.651052            0.027123
10       CN_Spec  0.843683            0.005636
11         CN_F1  0.691609            0.018316
12      MCI_Prec  0.516529            0.023961
13       MCI_Rec  0.597023            0.032449
14      MCI_Spec  0.729754            0.015743
15        MCI_F1  0.553759            0.026308
16       AD_Prec  0.848393            0.034040
17        AD_Rec  0.837159            0.012602
18       AD_Spec  0.944061            0.014641
19         AD_F1  0.842413            0.017463

In [ ]:
from sklearn.ensemble import RandomForestClassifier
import gc

print("=" * 60)
print("RANDOM FOREST")
print("=" * 60)

random_forest_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr_f, Xte_f = X.iloc[tr_idx], X.iloc[te_idx]
    ytr_f, yte_f = y.iloc[tr_idx], y.iloc[te_idx]
    Xtr_i, Xte_i = median_impute(Xtr_f, Xte_f)

    model = RandomForestClassifier(n_estimators=300, random_state=RANDOM_SEED, class_weight="balanced", n_jobs=N_JOBS)
    model.fit(Xtr_i, ytr_f)

    pred = model.predict(Xte_i)
    proba = align_probabilities(model.predict_proba(Xte_i), model.classes_)

    m = compute_metrics(yte_f, pred, proba)
    random_forest_results.append(m)
    # Consistently use 'AUC_Macro' to match compute_metrics output
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

# Display summary including Confusion Matrix
display_model_execution_summary("Random Forest", random_forest_results, X)

# Print Final Classification Report for the last fold
print("\nClassification Report (Last Fold):")
print(classification_report(yte_f, pred, target_names=['CN','MCI','AD']))

save_model_results("Random Forest", random_forest_results, "random_forest_results.csv")

============================================================
RANDOM FOREST
============================================================
Fold 1: AUC=0.8763, LogLoss=0.6356
Fold 2: AUC=0.8954, LogLoss=0.5922
Fold 3: AUC=0.8893, LogLoss=0.6012
Fold 4: AUC=0.8792, LogLoss=0.6729
Fold 5: AUC=0.8879, LogLoss=0.6993

==================== Random Forest EVALUATION ====================

           Mean Value
AUC_Macro    0.885617
Accuracy     0.743784
F1_Macro     0.742669
MCC          0.610609
Brier        0.118212
LogLoss      0.640227

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.77      0.80      0.78       299
         MCI       0.65      0.58      0.61       241
          AD       0.85      0.91      0.88       200

    accuracy                           0.76       740
   macro avg       0.76      0.76      0.76       740
weighted avg       0.75      0.76      0.75       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.743784            0.017764
1   Balanced_Acc  0.744216            0.018834
2       F1_Macro  0.742669            0.018095
3      AUC_Macro  0.885617            0.007771
4            MCC  0.610609            0.027558
5        LogLoss  0.640227            0.045864
6          Brier  0.118212            0.004201
7            ECE  0.033403            0.009757
8        CN_Prec  0.747757            0.013985
9         CN_Rec  0.822525            0.027857
10       CN_Spec  0.811976            0.016830
11         CN_F1  0.783047            0.011788
12      MCI_Prec  0.632490            0.034122
13       MCI_Rec  0.548959            0.028134
14      MCI_Spec  0.845225            0.020150
15        MCI_F1  0.587438            0.026583
16       AD_Prec  0.854582            0.019288
17        AD_Rec  0.861164            0.034380
18       AD_Spec  0.945540            0.008104
19         AD_F1  0.857522            0.019880

In [ ]:
from lightgbm import LGBMClassifier
import gc

print("=" * 60)
print("LIGHTGBM")
print("=" * 60)

lightgbm_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]
    Xtr_i, Xte_i = median_impute(Xtr, Xte)

    model = LGBMClassifier(n_estimators=300, learning_rate=0.05, random_state=RANDOM_SEED, class_weight="balanced", n_jobs=N_JOBS, verbose=-1)
    model.fit(Xtr_i, ytr)

    pred = model.predict(Xte_i)
    proba = align_probabilities(model.predict_proba(Xte_i), model.classes_)

    m = compute_metrics(yte, pred, proba)
    lightgbm_results.append(m)
    # Fixed KeyError: Changed 'AUC' to 'AUC_Macro' to match compute_metrics output
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

display_model_execution_summary("LightGBM", lightgbm_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))
save_model_results("LightGBM", lightgbm_results, "lightgbm_results.csv")

============================================================
LIGHTGBM
============================================================
Fold 1: AUC=0.8757, LogLoss=0.7118
Fold 2: AUC=0.8995, LogLoss=0.6032
Fold 3: AUC=0.9008, LogLoss=0.6031
Fold 4: AUC=0.8791, LogLoss=0.6969
Fold 5: AUC=0.8857, LogLoss=0.6677

==================== LightGBM EVALUATION ====================

           Mean Value
AUC_Macro    0.888155
Accuracy     0.740811
F1_Macro     0.741516
MCC          0.605932
Brier        0.126436
LogLoss      0.656514

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.76      0.77      0.76       299
         MCI       0.61      0.58      0.59       241
          AD       0.85      0.89      0.87       200

    accuracy                           0.74       740
   macro avg       0.74      0.74      0.74       740
weighted avg       0.73      0.74      0.74       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.740811            0.028832
1   Balanced_Acc  0.742040            0.028357
2       F1_Macro  0.741516            0.028043
3      AUC_Macro  0.888155            0.011541
4            MCC  0.605932            0.044192
5        LogLoss  0.656514            0.051275
6          Brier  0.126436            0.010203
7            ECE  0.111770            0.019523
8        CN_Prec  0.759145            0.014355
9         CN_Rec  0.802438            0.044306
10       CN_Spec  0.827829            0.012968
11         CN_F1  0.779790            0.025207
12      MCI_Prec  0.621541            0.053930
13       MCI_Rec  0.575498            0.034679
14      MCI_Spec  0.828785            0.034022
15        MCI_F1  0.596882            0.036868
16       AD_Prec  0.848813            0.031241
17        AD_Rec  0.848184            0.045470
18       AD_Spec  0.943691            0.012709
19         AD_F1  0.847875            0.028792

In [ ]:
from catboost import CatBoostClassifier
import gc

print("=" * 60)
print("CATBOOST")
print("=" * 60)

catboost_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]
    Xtr_i, Xte_i = median_impute(Xtr, Xte)

    model = CatBoostClassifier(
        iterations=1000,
        learning_rate=0.03,
        depth=6,
        loss_function="MultiClass",
        auto_class_weights="Balanced",
        random_seed=RANDOM_SEED,
        verbose=False,
        thread_count=N_JOBS,
    )
    model.fit(Xtr_i, ytr)

    pred = model.predict(Xte_i).ravel().astype(int)
    classes = model.classes_.astype(int)
    proba = align_probabilities(model.predict_proba(Xte_i), classes)

    m = compute_metrics(yte, pred, proba)
    catboost_results.append(m)
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

display_model_execution_summary("CatBoost", catboost_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))
save_model_results("CatBoost", catboost_results, "catboost_results.csv")

============================================================
CATBOOST
============================================================
Fold 1: AUC=0.8839, LogLoss=0.5791
Fold 2: AUC=0.9082, LogLoss=0.5083
Fold 3: AUC=0.9082, LogLoss=0.5210
Fold 4: AUC=0.8909, LogLoss=0.5627
Fold 5: AUC=0.8951, LogLoss=0.5445

==================== CatBoost EVALUATION ====================

           Mean Value
AUC_Macro    0.897276
Accuracy     0.756486
F1_Macro     0.756678
MCC          0.630137
Brier        0.113119
LogLoss      0.543105

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.78      0.80      0.79       299
         MCI       0.65      0.60      0.62       241
          AD       0.84      0.90      0.87       200

    accuracy                           0.76       740
   macro avg       0.76      0.76      0.76       740
weighted avg       0.75      0.76      0.76       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.756486            0.012473
1   Balanced_Acc  0.758224            0.012746
2       F1_Macro  0.756678            0.011279
3      AUC_Macro  0.897276            0.010783
4            MCC  0.630137            0.019775
5        LogLoss  0.543105            0.029067
6          Brier  0.113119            0.006559
7            ECE  0.028495            0.009270
8        CN_Prec  0.776229            0.011919
9         CN_Rec  0.813802            0.028105
10       CN_Spec  0.840967            0.014892
11         CN_F1  0.794227            0.009864
12      MCI_Prec  0.646073            0.034502
13       MCI_Rec  0.593714            0.026722
14      MCI_Spec  0.841217            0.027253
15        MCI_F1  0.617809            0.012164
16       AD_Prec  0.850001            0.023381
17        AD_Rec  0.867154            0.033153
18       AD_Spec  0.942949            0.010720
19         AD_F1  0.857998            0.016393

In [ ]:
import torch
from pytorch_tabnet.tab_model import TabNetClassifier
clf = TabNetClassifier(device_name='cpu')
import gc

print("=" * 60)
print("TABNET")
print("=" * 60)

tabnet_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]
    Xtr_i, Xte_i = median_impute(Xtr, Xte)

    model = TabNetClassifier(verbose=0, seed=RANDOM_SEED, device_name="cpu")
    model.fit(Xtr_i.values, ytr.values, eval_set=[(Xte_i.values, yte.values)], patience=20, max_epochs=100)

    pred = model.predict(Xte_i.values)
    proba = align_probabilities(model.predict_proba(Xte_i.values), model.classes_)

    m = compute_metrics(yte, pred, proba)
    tabnet_results.append(m)
    # Fixed KeyError: Changed 'AUC' to 'AUC_Macro' to match compute_metrics output
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

display_model_execution_summary("TabNet", tabnet_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))
save_model_results("TabNet", tabnet_results, "tabnet_results.csv")

============================================================
TABNET
============================================================
Stop training because you reached max_epochs = 100 with best_epoch = 83 and best_val_0_accuracy = 0.72703
Fold 1: AUC=0.8563, LogLoss=0.6699

Early stopping occurred at epoch 21 with best_epoch = 1 and best_val_0_accuracy = 0.45405
Fold 2: AUC=0.5656, LogLoss=15.9396

Early stopping occurred at epoch 29 with best_epoch = 9 and best_val_0_accuracy = 0.48649
Fold 3: AUC=0.7076, LogLoss=2.3763

Early stopping occurred at epoch 48 with best_epoch = 28 and best_val_0_accuracy = 0.64189
Fold 4: AUC=0.7577, LogLoss=2.0481
Stop training because you reached max_epochs = 100 with best_epoch = 83 and best_val_0_accuracy = 0.67838
Fold 5: AUC=0.8215, LogLoss=0.7310

==================== TabNet EVALUATION ====================

           Mean Value
AUC_Macro    0.741717
Accuracy     0.597568
F1_Macro     0.558474
MCC          0.408392
Brier        0.220762
LogLoss      4.352992

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.66      0.85      0.74       299
         MCI       0.53      0.37      0.44       241
          AD       0.86      0.80      0.83       200

    accuracy                           0.68       740
   macro avg       0.68      0.67      0.67       740
weighted avg       0.67      0.68      0.67       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.597568            0.120613
1   Balanced_Acc  0.594408            0.113120
2       F1_Macro  0.558474            0.135537
3      AUC_Macro  0.741717            0.113945
4            MCC  0.408392            0.177665
5        LogLoss  4.352992            6.522128
6          Brier  0.220762            0.086883
7            ECE  0.264073            0.174965
8        CN_Prec  0.611056            0.088161
9         CN_Rec  0.764149            0.188220
10       CN_Spec  0.673746            0.087486
11         CN_F1  0.674607            0.116957
12      MCI_Prec  0.475556            0.108937
13       MCI_Rec  0.242718            0.201380
14      MCI_Spec  0.886105            0.061245
15        MCI_F1  0.294476            0.199633
16       AD_Prec  0.670713            0.221003
17        AD_Rec  0.776358            0.078239
18       AD_Spec  0.820257            0.161381
19         AD_F1  0.706340            0.149573

In [ ]:
from pytabkit import RealMLP_TD_Classifier
import gc

print("=" * 60)
print("REALMLP")
print("=" * 60)

realmlp_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]
    Xtr_i, Xte_i = median_impute(Xtr, Xte)

    model = RealMLP_TD_Classifier(random_state=RANDOM_SEED, device="cpu")
    model.fit(Xtr_i.values, ytr.values)

    pred = model.predict(Xte_i.values)
    proba = align_probabilities(model.predict_proba(Xte_i.values), model.classes_)

    m = compute_metrics(yte, pred, proba)
    realmlp_results.append(m)
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

display_model_execution_summary("RealMLP", realmlp_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))
save_model_results("RealMLP", realmlp_results, "realmlp_results.csv")

INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

============================================================
REALMLP
============================================================

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=256` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Fold 1: AUC=0.8697, LogLoss=0.6200

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=256` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Fold 2: AUC=0.8973, LogLoss=0.5463

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=256` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Fold 3: AUC=0.8924, LogLoss=0.5655

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=256` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Fold 4: AUC=0.8758, LogLoss=0.6203

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_epochs=256` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

Fold 5: AUC=0.8914, LogLoss=0.5669

==================== RealMLP EVALUATION ====================

           Mean Value
AUC_Macro    0.885291
Accuracy     0.742703
F1_Macro     0.736968
MCC          0.612001
Brier        0.118903
LogLoss      0.583806

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.73      0.88      0.80       299
         MCI       0.67      0.48      0.56       241
          AD       0.86      0.87      0.86       200

    accuracy                           0.75       740
   macro avg       0.75      0.74      0.74       740
weighted avg       0.74      0.75      0.74       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.742703            0.012297
1   Balanced_Acc  0.743298            0.015323
2       F1_Macro  0.736968            0.018425
3      AUC_Macro  0.885291            0.011892
4            MCC  0.612001            0.018057
5        LogLoss  0.583806            0.034179
6          Brier  0.118903            0.006942
7            ECE  0.034611            0.004379
8        CN_Prec  0.736292            0.015282
9         CN_Rec  0.837855            0.043467
10       CN_Spec  0.796082            0.025632
11         CN_F1  0.782992            0.011792
12      MCI_Prec  0.649738            0.029861
13       MCI_Rec  0.504948            0.072234
14      MCI_Spec  0.866465            0.033376
15        MCI_F1  0.564858            0.039903
16       AD_Prec  0.841885            0.039374
17        AD_Rec  0.887090            0.037752
18       AD_Spec  0.937391            0.019814
19         AD_F1  0.863053            0.025168

In [ ]:
print("=" * 60)
print("TABPFN 3.0")
print("=" * 60)

from tabpfn_client import TabPFNClassifier
from tabpfn_client.constants import ModelVersion
tabpfn_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]

    model = TabPFNClassifier.create_default_for_version(
        ModelVersion.V3,
        ignore_pretraining_limits=True,
    )
    model.fit(Xtr, ytr)



    pred = model.predict(Xte)
    proba = align_probabilities(model.predict_proba(Xte), model.classes_)

    m = compute_metrics(yte, pred, proba)
    tabpfn_results.append(m)
    # Fixed KeyError: use 'AUC_Macro' to match compute_metrics output
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

display_model_execution_summary("TabPFN 3.0", tabpfn_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))
save_model_results("TabPFN 3.0", tabpfn_results, "tabpfn_3.0_results.csv")

============================================================
TABPFN 3.0
============================================================
Fold 1: AUC=0.8891, LogLoss=0.5763
Fold 2: AUC=0.9097, LogLoss=0.5029
Fold 3: AUC=0.9062, LogLoss=0.5181
Fold 4: AUC=0.8959, LogLoss=0.5442
Fold 5: AUC=0.9056, LogLoss=0.5140

==================== TabPFN 3.0 EVALUATION ====================

           Mean Value
AUC_Macro    0.901307
Accuracy     0.758378
F1_Macro     0.755053
MCC          0.633535
Brier        0.110228
LogLoss      0.531092

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.76      0.85      0.80       299
         MCI       0.68      0.56      0.62       241
          AD       0.87      0.90      0.88       200

    accuracy                           0.77       740
   macro avg       0.77      0.77      0.77       740
weighted avg       0.76      0.77      0.76       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.758378            0.010309
1   Balanced_Acc  0.756365            0.011191
2       F1_Macro  0.755053            0.010992
3      AUC_Macro  0.901307            0.008564
4            MCC  0.633535            0.016355
5        LogLoss  0.531092            0.029472
6          Brier  0.110228            0.005323
7            ECE  0.027445            0.008323
8        CN_Prec  0.752417            0.012985
9         CN_Rec  0.858008            0.013687
10       CN_Spec  0.808798            0.013977
11         CN_F1  0.801636            0.007859
12      MCI_Prec  0.664788            0.023465
13       MCI_Rec  0.548928            0.017475
14      MCI_Spec  0.865674            0.015441
15        MCI_F1  0.601002            0.012835
16       AD_Prec  0.863539            0.028080
17        AD_Rec  0.862159            0.030804
18       AD_Spec  0.949246            0.011513
19         AD_F1  0.862521            0.022484

In [ ]:
print("=" * 60)
print("TABPFN v2.5 ")
print("=" * 60)

from tabpfn_client import TabPFNClassifier
from tabpfn_client.constants import ModelVersion

# Initialize an empty list to store results
additional_tabpfn_results = []

# Loop through each fold of stratified k-fold cross-validation
for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):

    # Split data
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]

    # ==========================================================
    # EXPLICITLY USE TABPFN v2.5
    # ==========================================================
    model = TabPFNClassifier.create_default_for_version(
        ModelVersion.V2_5
    )

    # Fit model
    model.fit(Xtr, ytr)

    # Predictions
    pred = model.predict(Xte)

    # Probabilities
    proba_raw = model.predict_proba(Xte)

    # Align probabilities with common class labels
    proba = align_probabilities(
        proba_raw,
        model.classes_
    )

    # Compute metrics
    m = compute_metrics(yte, pred, proba)
    additional_tabpfn_results.append(m)

    # Print fold results
    print(
        f"Fold {fold}: "
        f"AUC={m['AUC_Macro']:.4f}, "
        f"LogLoss={m['LogLoss']:.4f}"
    )

    # Verify model used by Prior Labs
    try:
        print("Model metadata:", model._last_meta)
    except Exception as e:
        print("Could not display model metadata:", e)


# Display summary
display_model_execution_summary(
    "TABPFN v2.5 ",
    additional_tabpfn_results,
    X
)

# Classification report for last fold
print("\nClassification Report (Last Fold):")
print(
    classification_report(
        yte,
        pred,
        target_names=["CN", "MCI", "AD"]
    )
)

# Save results
save_model_results(
    "TABPFN v2.5",
    additional_tabpfn_results,
    "tabpfn_2.5_results.csv"
)

============================================================
TABPFN v2.5
============================================================
Fold 1: AUC=0.8872, LogLoss=0.5842
Model metadata: {'test_set_num_rows': 740, 'test_set_num_cols': 26, 'n_estimators': 8, 'billing_model_version': 'v2.5', 'execution_mode': 'standard', 'cache_outcome': 'not_requested', 'task': 'classification', 'package_version': '9.0.0', 'tabpfn_config': {'categorical_features_indices': [], 'average_before_softmax': False, 'random_state': 0, 'inference_config': {'TRANSFORM_DATES': False, 'TRANSFORM_TEXT': False}, 'inference_precision': 'auto', 'ignore_pretraining_limits': False, 'fit_mode': 'fit_preprocessors', 'model_path': '/app/tabpfn_models/tabpfn-v2.5-classifier-v2.5_default.ckpt', 'balance_probabilities': False}, 'classes': [0, 1, 2]}
Fold 2: AUC=0.9122, LogLoss=0.4994
Model metadata: {'test_set_num_rows': 740, 'test_set_num_cols': 26, 'n_estimators': 8, 'billing_model_version': 'v2.5', 'execution_mode': 'standard', 'cache_outcome': 'not_requested', 'task': 'classification', 'package_version': '9.0.0', 'tabpfn_config': {'categorical_features_indices': [], 'average_before_softmax': False, 'random_state': 0, 'inference_config': {'TRANSFORM_DATES': False, 'TRANSFORM_TEXT': False}, 'inference_precision': 'auto', 'ignore_pretraining_limits': False, 'fit_mode': 'fit_preprocessors', 'model_path': '/app/tabpfn_models/tabpfn-v2.5-classifier-v2.5_default.ckpt', 'balance_probabilities': False}, 'classes': [0, 1, 2]}
Fold 3: AUC=0.9088, LogLoss=0.5124
Model metadata: {'test_set_num_rows': 740, 'test_set_num_cols': 26, 'n_estimators': 8, 'billing_model_version': 'v2.5', 'execution_mode': 'standard', 'cache_outcome': 'not_requested', 'task': 'classification', 'package_version': '9.0.0', 'tabpfn_config': {'categorical_features_indices': [], 'average_before_softmax': False, 'random_state': 0, 'inference_config': {'TRANSFORM_DATES': False, 'TRANSFORM_TEXT': False}, 'inference_precision': 'auto', 'ignore_pretraining_limits': False, 'fit_mode': 'fit_preprocessors', 'model_path': '/app/tabpfn_models/tabpfn-v2.5-classifier-v2.5_default.ckpt', 'balance_probabilities': False}, 'classes': [0, 1, 2]}
Fold 4: AUC=0.8974, LogLoss=0.5379
Model metadata: {'test_set_num_rows': 740, 'test_set_num_cols': 26, 'n_estimators': 8, 'billing_model_version': 'v2.5', 'execution_mode': 'standard', 'cache_outcome': 'not_requested', 'task': 'classification', 'package_version': '9.0.0', 'tabpfn_config': {'categorical_features_indices': [], 'average_before_softmax': False, 'random_state': 0, 'inference_config': {'TRANSFORM_DATES': False, 'TRANSFORM_TEXT': False}, 'inference_precision': 'auto', 'ignore_pretraining_limits': False, 'fit_mode': 'fit_preprocessors', 'model_path': '/app/tabpfn_models/tabpfn-v2.5-classifier-v2.5_default.ckpt', 'balance_probabilities': False}, 'classes': [0, 1, 2]}
Fold 5: AUC=0.9054, LogLoss=0.5182
Model metadata: {'test_set_num_rows': 740, 'test_set_num_cols': 26, 'n_estimators': 8, 'billing_model_version': 'v2.5', 'execution_mode': 'standard', 'cache_outcome': 'not_requested', 'task': 'classification', 'package_version': '9.0.0', 'tabpfn_config': {'categorical_features_indices': [], 'average_before_softmax': False, 'random_state': 0, 'inference_config': {'TRANSFORM_DATES': False, 'TRANSFORM_TEXT': False}, 'inference_precision': 'auto', 'ignore_pretraining_limits': False, 'fit_mode': 'fit_preprocessors', 'model_path': '/app/tabpfn_models/tabpfn-v2.5-classifier-v2.5_default.ckpt', 'balance_probabilities': False}, 'classes': [0, 1, 2]}

==================== TABPFN v2.5  EVALUATION ====================

           Mean Value
AUC_Macro    0.902206
Accuracy     0.760000
F1_Macro     0.757077
MCC          0.635862
Brier        0.109811
LogLoss      0.530403

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.77      0.85      0.81       299
         MCI       0.69      0.57      0.62       241
          AD       0.85      0.90      0.87       200

    accuracy                           0.77       740
   macro avg       0.77      0.77      0.77       740
weighted avg       0.77      0.77      0.77       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.760000            0.014447
1   Balanced_Acc  0.758839            0.015282
2       F1_Macro  0.757077            0.014566
3      AUC_Macro  0.902206            0.010034
4            MCC  0.635862            0.022797
5        LogLoss  0.530403            0.033097
6          Brier  0.109811            0.005918
7            ECE  0.026335            0.016233
8        CN_Prec  0.761676            0.013378
9         CN_Rec  0.850648            0.017215
10       CN_Spec  0.819676            0.014916
11         CN_F1  0.803532            0.007379
12      MCI_Prec  0.664387            0.033333
13       MCI_Rec  0.559710            0.012524
14      MCI_Spec  0.862467            0.020637
15        MCI_F1  0.607224            0.016225
16       AD_Prec  0.855961            0.032092
17        AD_Rec  0.866159            0.035809
18       AD_Spec  0.945543            0.013685
19         AD_F1  0.860475            0.023087

In [ ]:
import importlib.metadata
print(importlib.metadata.version("tabpfn-client"))

from tabpfn_client.constants import ModelVersion
print(list(ModelVersion))

0.6.0
[<ModelVersion.V2: 'v2'>, <ModelVersion.V2_5: 'v2.5'>, <ModelVersion.V2_6: 'v2.6'>, <ModelVersion.V3: 'v3'>, <ModelVersion.V3_5: 'v3.5'>, <ModelVersion.V3_5_FAST: 'v3.5-fast'>]

In [ ]:
print("=" * 60)
print("TABPFN 3.5")
print("=" * 60)

from tabpfn_client import TabPFNClassifier
from tabpfn_client.constants import ModelVersion

tabpfn_35_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]

    model = TabPFNClassifier.create_default_for_version(
        ModelVersion.V3_5,
        ignore_pretraining_limits=True,
    )
    model.fit(Xtr, ytr)

    pred = model.predict(Xte)
    proba = align_probabilities(model.predict_proba(Xte), model.classes_)

    m = compute_metrics(yte, pred, proba)
    tabpfn_35_results.append(m)
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")

display_model_execution_summary("TabPFN 3.5", tabpfn_35_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))
save_model_results("TabPFN 3.5", tabpfn_35_results, "tabpfn_3.5_results.csv")

============================================================
TABPFN 3.5
============================================================
Fold 1: AUC=0.8881, LogLoss=0.5736
Fold 2: AUC=0.9122, LogLoss=0.5003
Fold 3: AUC=0.9075, LogLoss=0.5125
Fold 4: AUC=0.8976, LogLoss=0.5378
Fold 5: AUC=0.9056, LogLoss=0.5149

==================== TabPFN 3.5 EVALUATION ====================

           Mean Value
AUC_Macro    0.902191
Accuracy     0.760000
F1_Macro     0.757085
MCC          0.635776
Brier        0.109777
LogLoss      0.527813

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.76      0.86      0.80       299
         MCI       0.70      0.57      0.63       241
          AD       0.88      0.90      0.89       200

    accuracy                           0.77       740
   macro avg       0.78      0.77      0.77       740
weighted avg       0.77      0.77      0.77       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.760000            0.015336
1   Balanced_Acc  0.757959            0.016239
2       F1_Macro  0.757085            0.015989
3      AUC_Macro  0.902191            0.009482
4            MCC  0.635776            0.024226
5        LogLoss  0.527813            0.028940
6          Brier  0.109777            0.005560
7            ECE  0.022718            0.010283
8        CN_Prec  0.756499            0.013550
9         CN_Rec  0.856656            0.013390
10       CN_Spec  0.813325            0.012906
11         CN_F1  0.803400            0.010642
12      MCI_Prec  0.666497            0.036301
13       MCI_Rec  0.558057            0.018479
14      MCI_Spec  0.864065            0.021631
15        MCI_F1  0.607036            0.019299
16       AD_Prec  0.863276            0.033334
17        AD_Rec  0.859164            0.035111
18       AD_Spec  0.949247            0.013563
19         AD_F1  0.860820            0.027129

In [ ]:
import shutil
from autogluon.tabular import TabularPredictor

print("=" * 60)
print("AUTOGLUON")
print("=" * 60)

autogluon_results = []
autogluon_skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)
autogluon_root = os.path.join(OUTPUT_DIR, "autogluon_models")
os.makedirs(autogluon_root, exist_ok=True)

for fold_number, (train_index, test_index) in enumerate(autogluon_skf.split(X, y), start=1):
    X_train_f = X.iloc[train_index].copy().reset_index(drop=True)
    X_test_f = X.iloc[test_index].copy().reset_index(drop=True)
    y_train_f = y.iloc[train_index].copy().reset_index(drop=True)
    y_test_f = y.iloc[test_index].copy().reset_index(drop=True)

    train_data = X_train_f.copy()
    train_data["label"] = y_train_f
    fold_path = os.path.join(autogluon_root, f"fold_{fold_number}")
    if os.path.exists(fold_path): shutil.rmtree(fold_path)

    predictor = TabularPredictor(label="label", problem_type="multiclass", eval_metric="accuracy", path=fold_path, verbosity=0)
    predictor.fit(train_data=train_data, presets="medium_quality", num_gpus=0)

    pred = predictor.predict(X_test_f).to_numpy(dtype=int)
    proba = align_probabilities(predictor.predict_proba(X_test_f).to_numpy(), predictor.class_labels)

    m = compute_metrics(y_test_f, pred, proba)
    autogluon_results.append(m)
    # Fixed KeyError: Changed 'AUC' to 'AUC_Macro' to match compute_metrics output
    print(f"Fold {fold_number}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f}")
    del predictor
    gc.collect()

display_model_execution_summary("AutoGluon", autogluon_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(y_test_f, pred, target_names=['CN','MCI','AD']))
save_model_results("AutoGluon", autogluon_results, "autogluon_results.csv")

============================================================
AUTOGLUON
============================================================

KeyboardInterrupt:

In [ ]:
!pip install -q "torch==2.5.1" --index-url https://download.pytorch.org/whl/cu121

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 MB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 77.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 207.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 188.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 82.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 128.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 154.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 131.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 112.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 121.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 89.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 191.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 54.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.26.0+cpu requires torch==2.11.0, but you have torch 2.5.1+cu121 which is incompatible.

In [ ]:
!pip install -q "autogluon.tabular[mitra]==1.6.3"
!pip install -q loguru

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.6/526.6 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.2/366.2 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.1/170.1 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.0/206.0 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 39.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.7/197.7 MB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 129.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 MB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 89.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.1/214.1 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 53.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 MB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.9/200.9 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.9/145.9 MB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.0/148.0 kB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 116.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 98.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 MB 35.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.26.0+cpu requires torch==2.11.0, but you have torch 2.13.0 which is incompatible.

In [ ]:
from huggingface_hub import login
from getpass import getpass

HF_TOKEN = getpass("Paste your HuggingFace token: ")
login(token=HF_TOKEN)

Paste your HuggingFace token: ··········

In [ ]:
import shutil
import time
from autogluon.tabular import TabularPredictor

print("=" * 60)
print("MITRA (via AutoGluon)")
print("=" * 60)


mitra_results = []
mitra_skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)
mitra_root = os.path.join(OUTPUT_DIR, "mitra_models")
os.makedirs(mitra_root, exist_ok=True)

for fold_number, (train_index, test_index) in enumerate(mitra_skf.split(X, y), start=1):
    fold_start = time.time()
    print(f"\n--- Fold {fold_number} starting ---")

    X_train_f = X.iloc[train_index].copy().reset_index(drop=True)
    X_test_f = X.iloc[test_index].copy().reset_index(drop=True)
    y_train_f = y.iloc[train_index].copy().reset_index(drop=True)
    y_test_f = y.iloc[test_index].copy().reset_index(drop=True)

    train_data = X_train_f.copy()
    train_data["label"] = y_train_f
    fold_path = os.path.join(mitra_root, f"fold_{fold_number}")
    if os.path.exists(fold_path): shutil.rmtree(fold_path)

    predictor = TabularPredictor(
        label="label", problem_type="multiclass", eval_metric="accuracy",
        path=fold_path, verbosity=2,   # was 0 — turned up so download/train progress prints
    )
    # Restrict AutoGluon to the MITRA model only, no ensembling with other
    # models, so this is a clean single-model comparison point like the
    # other rows in E1.
    predictor.fit(
    train_data=train_data,
    hyperparameters={"MITRA": {"fine_tune": False}},
    num_gpus=0,
)

    pred = predictor.predict(X_test_f).to_numpy(dtype=int)
    proba = align_probabilities(predictor.predict_proba(X_test_f).to_numpy(), predictor.class_labels)

    m = compute_metrics(y_test_f, pred, proba)
    mitra_results.append(m)
    elapsed = time.time() - fold_start
    print(f"Fold {fold_number}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f} (took {elapsed:.1f}s)")
    del predictor
    gc.collect()

display_model_execution_summary("MITRA", mitra_results, X)
print("\nClassification Report (Last Fold):")
print(classification_report(y_test_f, pred, target_names=['CN','MCI','AD']))
save_model_results("MITRA", mitra_results, "mitra_results.csv")

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.13.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          8
Pytorch Version:    2.11.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       48.28 GB / 50.99 GB (94.7%)
Disk Space Avail:   194.07 GB / 225.83 GB (85.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.

============================================================
MITRA (via AutoGluon)
============================================================

--- Fold 1 starting ---

Beginning AutoGluon training ...
AutoGluon will save models to "/content/ADNI results/mitra_models/fold_1"
Train Data Rows:    2960
Train Data Columns: 26
Label Column:       label
Problem Type:       multiclass
Preprocessing data...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    49357.36 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	0.1s = Fit runtime
	26 features in original data used to generate 26 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1689, Train Rows: 2460, Val Rows: 500
User-specified model hyperparameters to be fit:
{
	'MITRA': [{'fine_tune': False}],
}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: Mitra ...
	Fitting with cpus=4, gpus=0, mem=9.5/48.2 GB
	WARNING: Mitra is fitting on CPU because no CUDA GPU is available on this machine. This model attends over the training context for every prediction, so a CPU fit is typically an order of magnitude slower than on GPU (measured 12-63x end to end) and may appear to hang. Pass `num_gpus=0` explicitly to silence this warning.

config.json:   0%|          | 0.00/86.0 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  303MB

model.safetensors: downloading bytes:           |  0.00B

	0.758	 = Validation score   (accuracy)
	806.59s	 = Training   runtime
	867.5s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/47.0 GB
	Ensemble Weights: {'Mitra': 1.0}
	0.758	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1674.84s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 0.6 rows/s (500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/ADNI results/mitra_models/fold_1")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.13.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          8
Pytorch Version:    2.11.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       47.07 GB / 50.99 GB (92.3%)
Disk Space Avail:   193.49 GB / 225.83 GB (85.7%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.

Fold 1: AUC=0.8870, LogLoss=0.5800 (took 3510.0s)

--- Fold 2 starting ---

Beginning AutoGluon training ...
AutoGluon will save models to "/content/ADNI results/mitra_models/fold_2"
Train Data Rows:    2960
Train Data Columns: 26
Label Column:       label
Problem Type:       multiclass
Preprocessing data...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    48199.26 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	0.1s = Fit runtime
	26 features in original data used to generate 26 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.08s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1689, Train Rows: 2460, Val Rows: 500
User-specified model hyperparameters to be fit:
{
	'MITRA': [{'fine_tune': False}],
}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: Mitra ...
	Fitting with cpus=4, gpus=0, mem=9.5/47.1 GB
	WARNING: Mitra is fitting on CPU because no CUDA GPU is available on this machine. This model attends over the training context for every prediction, so a CPU fit is typically an order of magnitude slower than on GPU (measured 12-63x end to end) and may appear to hang. Pass `num_gpus=0` explicitly to silence this warning.
	0.764	 = Validation score   (accuracy)
	839.06s	 = Training   runtime
	814.62s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/47.0 GB
	Ensemble Weights: {'Mitra': 1.0}
	0.764	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1654.21s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 0.6 rows/s (500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/ADNI results/mitra_models/fold_2")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.13.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          8
Pytorch Version:    2.11.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       47.07 GB / 50.99 GB (92.3%)
Disk Space Avail:   193.21 GB / 225.83 GB (85.6%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.

Fold 2: AUC=0.8994, LogLoss=0.5406 (took 3397.7s)

--- Fold 3 starting ---

Beginning AutoGluon training ...
AutoGluon will save models to "/content/ADNI results/mitra_models/fold_3"
Train Data Rows:    2960
Train Data Columns: 26
Label Column:       label
Problem Type:       multiclass
Preprocessing data...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    48187.23 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	0.1s = Fit runtime
	26 features in original data used to generate 26 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.08s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1689, Train Rows: 2460, Val Rows: 500
User-specified model hyperparameters to be fit:
{
	'MITRA': [{'fine_tune': False}],
}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: Mitra ...
	Fitting with cpus=4, gpus=0, mem=9.5/47.1 GB
	WARNING: Mitra is fitting on CPU because no CUDA GPU is available on this machine. This model attends over the training context for every prediction, so a CPU fit is typically an order of magnitude slower than on GPU (measured 12-63x end to end) and may appear to hang. Pass `num_gpus=0` explicitly to silence this warning.
	0.76	 = Validation score   (accuracy)
	799.7s	 = Training   runtime
	795.34s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/47.1 GB
	Ensemble Weights: {'Mitra': 1.0}
	0.76	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1595.7s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 0.6 rows/s (500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/ADNI results/mitra_models/fold_3")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.13.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          8
Pytorch Version:    2.11.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       47.05 GB / 50.99 GB (92.3%)
Disk Space Avail:   192.93 GB / 225.83 GB (85.4%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.

Fold 3: AUC=0.9003, LogLoss=0.5361 (took 3276.7s)

--- Fold 4 starting ---

Beginning AutoGluon training ...
AutoGluon will save models to "/content/ADNI results/mitra_models/fold_4"
Train Data Rows:    2960
Train Data Columns: 26
Label Column:       label
Problem Type:       multiclass
Preprocessing data...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    48181.66 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	0.1s = Fit runtime
	26 features in original data used to generate 26 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.08s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1689, Train Rows: 2460, Val Rows: 500
User-specified model hyperparameters to be fit:
{
	'MITRA': [{'fine_tune': False}],
}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: Mitra ...
	Fitting with cpus=4, gpus=0, mem=9.5/47.1 GB
	WARNING: Mitra is fitting on CPU because no CUDA GPU is available on this machine. This model attends over the training context for every prediction, so a CPU fit is typically an order of magnitude slower than on GPU (measured 12-63x end to end) and may appear to hang. Pass `num_gpus=0` explicitly to silence this warning.
	0.748	 = Validation score   (accuracy)
	772.8s	 = Training   runtime
	763.94s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/47.1 GB
	Ensemble Weights: {'Mitra': 1.0}
	0.748	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1537.3s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 0.7 rows/s (500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/ADNI results/mitra_models/fold_4")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.13.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          8
Pytorch Version:    2.11.0+cpu
CUDA Version:       CUDA is not available
Memory Avail:       47.07 GB / 50.99 GB (92.3%)
Disk Space Avail:   192.64 GB / 225.83 GB (85.3%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : Use this if you have a GPU. The go-to preset for best results, and the one to use for benchmark comparisons. New in v1.6: far better than 'best' on datasets <100000 samples by using Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: Nori, TabICLv2, and TabDPT-Turbo. Every model is free for commercial use. Requires `pip install autogluon.tabular[tabarena]`.
	presets='noncommercial': New in v1.6: 'extreme' plus TabPFN-3, a frontier tabular foundation model created by Prior Labs. Stronger still, but commercial use requires a TabPFN-3 license: https://docs.priorlabs.ai/models#tabpfn-model-license
	presets='best'     : Use this if you do not have a GPU. Maximize accuracy. Use in competitions.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.

Fold 4: AUC=0.8833, LogLoss=0.5733 (took 3190.8s)

--- Fold 5 starting ---

Beginning AutoGluon training ...
AutoGluon will save models to "/content/ADNI results/mitra_models/fold_5"
Train Data Rows:    2960
Train Data Columns: 26
Label Column:       label
Problem Type:       multiclass
Preprocessing data...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    48200.25 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 25 | ['ADAS_TOTSCORE', 'ADAS_TOTAL13', 'FAQ_FAQTOTAL', 'MMSE_MMSCORE', 'MOCA_MOCA', ...]
		('int', [])   :  1 | ['AGE']
	0.1s = Fit runtime
	26 features in original data used to generate 26 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.09s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1689, Train Rows: 2460, Val Rows: 500
User-specified model hyperparameters to be fit:
{
	'MITRA': [{'fine_tune': False}],
}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: Mitra ...
	Fitting with cpus=4, gpus=0, mem=9.5/47.1 GB
	WARNING: Mitra is fitting on CPU because no CUDA GPU is available on this machine. This model attends over the training context for every prediction, so a CPU fit is typically an order of magnitude slower than on GPU (measured 12-63x end to end) and may appear to hang. Pass `num_gpus=0` explicitly to silence this warning.
	0.746	 = Validation score   (accuracy)
	769.57s	 = Training   runtime
	760.55s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=8, gpus=0, mem=0.0/47.0 GB
	Ensemble Weights: {'Mitra': 1.0}
	0.746	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1530.72s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 0.7 rows/s (500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/ADNI results/mitra_models/fold_5")

Fold 5: AUC=0.8989, LogLoss=0.5355 (took 3163.4s)

==================== MITRA EVALUATION ====================

           Mean Value
AUC_Macro    0.893792
Accuracy     0.745676
F1_Macro     0.742109
MCC          0.613956
Brier        0.115072
LogLoss      0.553100

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.74      0.83      0.78       299
         MCI       0.66      0.56      0.60       241
          AD       0.89      0.89      0.89       200

    accuracy                           0.76       740
   macro avg       0.76      0.76      0.76       740
weighted avg       0.75      0.76      0.75       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.745676            0.015655
1   Balanced_Acc  0.741272            0.018404
2       F1_Macro  0.742109            0.017863
3      AUC_Macro  0.893792            0.007991
4            MCC  0.613956            0.024248
5        LogLoss  0.553100            0.021719
6          Brier  0.115072            0.004728
7            ECE  0.039139            0.010306
8        CN_Prec  0.734420            0.015172
9         CN_Rec  0.863390            0.024580
10       CN_Spec  0.788417            0.019095
11         CN_F1  0.793436            0.010957
12      MCI_Prec  0.640649            0.031186
13       MCI_Rec  0.528223            0.024342
14      MCI_Spec  0.856454            0.015768
15        MCI_F1  0.578863            0.025146
16       AD_Prec  0.878213            0.029771
17        AD_Rec  0.832204            0.046248
18       AD_Spec  0.957026            0.011354
19         AD_F1  0.854030            0.030878

In [ ]:
import gc
from xgboost import XGBClassifier
from sklearn.metrics import classification_report

print("=" * 60)
print("XGBOOST")
print("=" * 60)

xgboost_results = []

for fold, (tr_idx, te_idx) in enumerate(skf.split(X, y), 1):
    Xtr, Xte = X.iloc[tr_idx], X.iloc[te_idx]
    ytr, yte = y.iloc[tr_idx], y.iloc[te_idx]
    Xtr_i, Xte_i = median_impute(Xtr, Xte)

    model = XGBClassifier(n_estimators=1000, learning_rate=0.03, max_depth=6, device="cpu", tree_method="hist", random_state=RANDOM_SEED, n_jobs=N_JOBS)
    model.fit(Xtr_i, ytr)

    pred = model.predict(Xte_i)
    proba = align_probabilities(model.predict_proba(Xte_i), model.classes_)

    m = compute_metrics(yte, pred, proba)
    xgboost_results.append(m)
    print(f"Fold {fold}: AUC={m['AUC_Macro']:.4f}, LogLoss={m['LogLoss']:.4f})")

display_model_execution_summary("XGBoost", xgboost_results, X)

print("\nClassification Report (Last Fold):")
print(classification_report(yte, pred, target_names=['CN','MCI','AD']))

save_model_results("XGBoost", xgboost_results, "xgboost_results.csv")

============================================================
XGBOOST
============================================================
[05:08:02] WARNING: ../src/learner.cc:767:
Parameters: { "device" } are not used.

Fold 1: AUC=0.8771, LogLoss=0.7068)
[05:08:06] WARNING: ../src/learner.cc:767:
Parameters: { "device" } are not used.

Fold 2: AUC=0.9040, LogLoss=0.5806)
[05:08:09] WARNING: ../src/learner.cc:767:
Parameters: { "device" } are not used.

Fold 3: AUC=0.9041, LogLoss=0.5890)
[05:08:13] WARNING: ../src/learner.cc:767:
Parameters: { "device" } are not used.

Fold 4: AUC=0.8796, LogLoss=0.6839)
[05:08:17] WARNING: ../src/learner.cc:767:
Parameters: { "device" } are not used.

Fold 5: AUC=0.8852, LogLoss=0.6694)

==================== XGBoost EVALUATION ====================

           Mean Value
AUC_Macro    0.890023
Accuracy     0.744054
F1_Macro     0.743364
MCC          0.610643
Brier        0.123909
LogLoss      0.645941

Classification Report (Last Fold):
              precision    recall  f1-score   support

          CN       0.75      0.80      0.78       299
         MCI       0.63      0.55      0.59       241
          AD       0.83      0.89      0.86       200

    accuracy                           0.74       740
   macro avg       0.74      0.75      0.74       740
weighted avg       0.74      0.74      0.74       740

          Metric      Mean  Standard Deviation
0       Accuracy  0.744054            0.014320
1   Balanced_Acc  0.744241            0.014060
2       F1_Macro  0.743364            0.014554
3      AUC_Macro  0.890023            0.013136
4            MCC  0.610643            0.021879
5        LogLoss  0.645941            0.057476
6          Brier  0.123909            0.010030
7            ECE  0.101367            0.014420
8        CN_Prec  0.755598            0.008120
9         CN_Rec  0.817840            0.023519
10       CN_Spec  0.821031            0.008129
11         CN_F1  0.785358            0.012492
12      MCI_Prec  0.630286            0.025287
13       MCI_Rec  0.564699            0.023809
14      MCI_Spec  0.839612            0.014429
15        MCI_F1  0.595533            0.021933
16       AD_Prec  0.849460            0.026585
17        AD_Rec  0.850184            0.032351
18       AD_Spec  0.943691            0.012016
19         AD_F1  0.849200            0.014179

In [ ]:
import os
import pandas as pd
import numpy as np

result_files = {
    "Logistic Regression": "logistic_regression_results.csv",
    "Random Forest": "random_forest_results.csv",
    "XGBoost": "xgboost_results.csv",
    "LightGBM": "lightgbm_results.csv",
    "TabNet": "tabnet_results.csv",
    "TabPFN 3.0": "tabpfn_3.0_results.csv",
    "AutoGluon": "autogluon_results.csv",
    "TABPFN v2.5 ": "tabpfn_2.5_results.csv",
    "CatBoost": "catboost_results.csv", "RealMLP": "realmlp_results.csv",
    "MITRA": "mitra_results.csv",
    "TabPFN 3.5 ": "tabpfn_3.5_results.csv"
    # Added this line
}

combined_results = {}

for model_name, filename in result_files.items():
    filepath = os.path.join(OUTPUT_DIR, filename)

    if os.path.exists(filepath):
        result = pd.read_csv(filepath)
        model_data = {}
        for _, row in result.iterrows():
            m_name = row["Metric"]
            # Standardize names to the final requested labels
            if m_name == "Acc": m_name = "Accuracy"
            if m_name == "AUC": m_name = "AUC_Macro"

            model_data[m_name] = f"{row['Mean']:.4f} \u00B1 {row['Standard Deviation']:.4f}"

        combined_results[model_name] = model_data

if combined_results:
    final_results = pd.DataFrame(combined_results).T
    # Final display columns including Balanced Accuracy for consistency
    display_cols = ["AUC_Macro", "Accuracy", "Balanced_Acc", "F1_Macro", "MCC", "LogLoss", "Brier"]
    existing_cols = [c for c in display_cols if c in final_results.columns]
    final_results = final_results[existing_cols]

    final_path = os.path.join(OUTPUT_DIR, "E1_combined_benchmarking.csv")
    final_results.to_csv(final_path)

    print("\n" + "=" * 60)
    print("STANDARDIZED BENCHMARKING RESULTS")
    print("=" * 60)
    display(final_results)
else:
    print("No result files found.")

============================================================
STANDARDIZED BENCHMARKING RESULTS
============================================================

,AUC_Macro,Accuracy,Balanced_Acc,F1_Macro,MCC,LogLoss,Brier
Logistic Regression,0.8633 ± 0.0105,0.6838 ± 0.0169,0.6951 ± 0.0158,0.6959 ± 0.0173,0.5239 ± 0.0247,0.6294 ± 0.0260,0.1310 ± 0.0052
Random Forest,0.8856 ± 0.0078,0.7438 ± 0.0178,0.7442 ± 0.0188,0.7427 ± 0.0181,0.6106 ± 0.0276,0.6402 ± 0.0459,0.1182 ± 0.0042
XGBoost,0.8900 ± 0.0131,0.7441 ± 0.0143,0.7442 ± 0.0141,0.7434 ± 0.0146,0.6106 ± 0.0219,0.6459 ± 0.0575,0.1239 ± 0.0100
LightGBM,0.8882 ± 0.0115,0.7408 ± 0.0288,0.7420 ± 0.0284,0.7415 ± 0.0280,0.6059 ± 0.0442,0.6565 ± 0.0513,0.1264 ± 0.0102
TabNet,0.7417 ± 0.1139,0.5976 ± 0.1206,0.5944 ± 0.1131,0.5585 ± 0.1355,0.4084 ± 0.1777,4.3530 ± 6.5221,0.2208 ± 0.0869
TabPFN 3.0,0.9013 ± 0.0086,0.7584 ± 0.0103,0.7564 ± 0.0112,0.7551 ± 0.0110,0.6335 ± 0.0164,0.5311 ± 0.0295,0.1102 ± 0.0053
AutoGluon,0.8946 ± 0.0131,0.7481 ± 0.0176,0.7467 ± 0.0174,0.7452 ± 0.0173,0.6177 ± 0.0277,0.5834 ± 0.0393,0.1175 ± 0.0077
TABPFN v2.5,0.9022 ± 0.0100,0.7600 ± 0.0144,0.7588 ± 0.0153,0.7571 ± 0.0146,0.6359 ± 0.0228,0.5304 ± 0.0331,0.1098 ± 0.0059
CatBoost,0.8973 ± 0.0108,0.7565 ± 0.0125,0.7582 ± 0.0127,0.7567 ± 0.0113,0.6301 ± 0.0198,0.5431 ± 0.0291,0.1131 ± 0.0066
RealMLP,0.8853 ± 0.0119,0.7427 ± 0.0123,0.7433 ± 0.0153,0.7370 ± 0.0184,0.6120 ± 0.0181,0.5838 ± 0.0342,0.1189 ± 0.0069
MITRA,0.8938 ± 0.0080,0.7457 ± 0.0157,0.7413 ± 0.0184,0.7421 ± 0.0179,0.6140 ± 0.0242,0.5531 ± 0.0217,0.1151 ± 0.0047
TabPFN 3.5,0.9022 ± 0.0095,0.7600 ± 0.0153,0.7580 ± 0.0162,0.7571 ± 0.0160,0.6358 ± 0.0242,0.5278 ± 0.0289,0.1098 ± 0.0056

In [ ]:
import shutil
import os

# Define the name of the folder to zip and the output filename
folder_to_zip = OUTPUT_DIR # Already defined as 'ADNI results'
output_filename = 'frame_ad_results'

if os.path.exists(folder_to_zip):
    shutil.make_archive(output_filename, 'zip', folder_to_zip)
    print(f"✅ Successfully created {output_filename}.zip. You can download it from the file browser.")
else:
    print(f"❌ Error: The folder '{folder_to_zip}' was not found.")

✅ Successfully created frame_ad_results.zip. You can download it from the file browser.

##  Experiment 2: Multimodal Ablation

In [ ]:
# ============================================================
# EXPERIMENT 2: HELPER FUNCTION
# Evaluate one feature subset with 5-fold CV
# Run this cell before Experiment 2 and Experiment 5b
# ============================================================

import os
import gc
import numpy as np
import pandas as pd

metrics_to_collect = [
    "AUC_Macro",
    "Accuracy",
    "Balanced_Acc",
    "F1_Macro",
    "MCC",
    "LogLoss"
]

def evaluate_tabpfn_subset(feature_list):

    Xsub = X[feature_list]
    fold_metrics = []

    for fold_number, (tr_idx, te_idx) in enumerate(
        skf.split(Xsub, y), start=1
    ):
        Xtr = Xsub.iloc[tr_idx].copy()
        Xte = Xsub.iloc[te_idx].copy()
        ytr = y.iloc[tr_idx].copy()
        yte = y.iloc[te_idx].copy()

        clf = get_tabpfn()
        clf.fit(Xtr, ytr)
        raw_proba = clf.predict_proba(Xte)
        proba = align_probabilities(raw_proba, clf.classes_)
        pred = clf.predict(Xte)
        fold_result = compute_metrics(yte, pred, proba)
        fold_metrics.append(fold_result)
        del clf
        gc.collect()

    summary = {}
    for metric in metrics_to_collect:
        values = np.array(
            [result[metric] for result in fold_metrics], dtype=float
        )
        summary[f"{metric}_Mean"] = np.mean(values)
        summary[f"{metric}_SD"] = np.std(values, ddof=1)

    return summary

print("evaluate_tabpfn_subset is ready.")

evaluate_tabpfn_subset is ready.

In [ ]:
# ============================================================
# EXPERIMENT 2: SEQUENTIAL BACKWARD FEATURE ABLATION
# Start with all 26 features and remove one feature at a time
# ============================================================

print("=" * 70)
print("EXPERIMENT 2: SEQUENTIAL BACKWARD FEATURE ABLATION")
print("=" * 70)

import os
import gc
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# SETTINGS
# ------------------------------------------------------------

# Start with every feature available in X
current_features = list(X.columns)

# Stop when this many features remain
MIN_FEATURES = 1

# Metric used to decide which feature to remove
# IMPORTANT: must match your compute_metrics() output exactly
SELECTION_METRIC = "AUC_Macro"

# Metrics to save/report
metrics_to_collect = [
    "AUC_Macro",
    "Accuracy",
    "Balanced_Acc",
    "F1_Macro",
    "MCC",
    "LogLoss"
]

# ------------------------------------------------------------
# STORAGE
# ------------------------------------------------------------

e2_selection_history = []
e2_candidate_history = []

print(f"Starting number of features: {len(current_features)}")
print(f"Stopping at: {MIN_FEATURES} features")
print(f"Selection metric: {SELECTION_METRIC}")


# ------------------------------------------------------------
# HELPER FUNCTION
# Evaluate one feature subset with 5-fold CV
# ------------------------------------------------------------

def evaluate_tabpfn_subset(feature_list):

    Xsub = X[feature_list]

    fold_metrics = []

    for fold_number, (tr_idx, te_idx) in enumerate(
        skf.split(Xsub, y),
        start=1
    ):

        Xtr = Xsub.iloc[tr_idx].copy()
        Xte = Xsub.iloc[te_idx].copy()

        ytr = y.iloc[tr_idx].copy()
        yte = y.iloc[te_idx].copy()

        # Fresh TabPFN model for every fold
        clf = get_tabpfn()

        clf.fit(
            Xtr,
            ytr
        )

        raw_proba = clf.predict_proba(
            Xte
        )

        proba = align_probabilities(
            raw_proba,
            clf.classes_
        )

        pred = clf.predict(
            Xte
        )

        fold_result = compute_metrics(
            yte,
            pred,
            proba
        )

        fold_metrics.append(
            fold_result
        )

        del clf
        gc.collect()

    # Calculate mean and SD for each metric
    summary = {}

    for metric in metrics_to_collect:

        values = np.array(
            [result[metric] for result in fold_metrics],
            dtype=float
        )

        summary[f"{metric}_Mean"] = np.mean(values)
        summary[f"{metric}_SD"] = np.std(
            values,
            ddof=1
        )

    return summary


# ============================================================
# STEP 0: EVALUATE FULL 26-FEATURE MODEL
# ============================================================

print("\n" + "-" * 70)
print(f"Evaluating FULL model with {len(current_features)} features")
print("-" * 70)

full_summary = evaluate_tabpfn_subset(
    current_features
)

e2_selection_history.append({
    "Num_Features": len(current_features),
    "Removed_Feature": "None — Full Model",
    "Remaining_Features": " | ".join(current_features),
    **full_summary
})

print(
    f"Full model: "
    f"Macro F1={full_summary['F1_Macro_Mean']:.4f} | "
    f"AUC={full_summary['AUC_Macro_Mean']:.4f} | "
    f"Balanced Acc={full_summary['Balanced_Acc_Mean']:.4f}"
)


# ============================================================
# SEQUENTIAL BACKWARD ELIMINATION
# ============================================================

while len(current_features) > MIN_FEATURES:

    current_n = len(current_features)

    print("\n" + "=" * 70)
    print(
        f"Finding best {current_n - 1}-feature subset "
        f"from current {current_n} features"
    )
    print("=" * 70)

    candidate_results = []

    # --------------------------------------------------------
    # Try removing each currently available feature
    # --------------------------------------------------------

    for candidate_number, feature_to_remove in enumerate(
        current_features,
        start=1
    ):

        candidate_features = [
            feature
            for feature in current_features
            if feature != feature_to_remove
        ]

        print(
            f"[{candidate_number}/{current_n}] "
            f"Testing removal of: {feature_to_remove}"
        )

        try:

            summary = evaluate_tabpfn_subset(
                candidate_features
            )

            candidate_record = {
                "Starting_Num_Features": current_n,
                "Resulting_Num_Features": len(candidate_features),
                "Feature_Removed": feature_to_remove,
                "Remaining_Features": " | ".join(candidate_features),
                **summary
            }

            candidate_results.append(
                candidate_record
            )

            e2_candidate_history.append(
                candidate_record
            )

            print(
                f"    Macro F1="
                f"{summary['F1_Macro_Mean']:.4f} | "
                f"AUC="
                f"{summary['AUC_Macro_Mean']:.4f}"
            )

        except Exception as error:

            print(
                f"    FAILED when removing "
                f"{feature_to_remove}: {error}"
            )

            continue


    # --------------------------------------------------------
    # MAKE SURE AT LEAST ONE CANDIDATE WORKED
    # --------------------------------------------------------

    if len(candidate_results) == 0:

        raise RuntimeError(
            f"No valid candidate subsets were produced "
            f"when starting with {current_n} features."
        )


    # --------------------------------------------------------
    # SELECT BEST CANDIDATE
    # # Highest Macro AUC wins
    # --------------------------------------------------------

    best_candidate = max(
        candidate_results,
        key=lambda result:
            result[f"{SELECTION_METRIC}_Mean"]
    )


    best_removed_feature = best_candidate[
        "Feature_Removed"
    ]

    # Permanently remove selected feature
    current_features.remove(
        best_removed_feature
    )


    # --------------------------------------------------------
    # SAVE SELECTED SUBSET
    # --------------------------------------------------------

    selected_record = {
        "Num_Features": len(current_features),
        "Removed_Feature": best_removed_feature,
        "Remaining_Features": " | ".join(current_features)
    }

    for metric in metrics_to_collect:

        selected_record[
            f"{metric}_Mean"
        ] = best_candidate[
            f"{metric}_Mean"
        ]

        selected_record[
            f"{metric}_SD"
        ] = best_candidate[
            f"{metric}_SD"
        ]


    e2_selection_history.append(
        selected_record
    )


    print("\n*** SELECTED REMOVAL ***")

    print(
        f"Removed: {best_removed_feature}"
    )

    print(
        f"Remaining features: {len(current_features)}"
    )

    print(
        f"Macro F1="
        f"{best_candidate['F1_Macro_Mean']:.4f}"
    )

    print(
        f"Macro AUC="
        f"{best_candidate['AUC_Macro_Mean']:.4f}"
    )

    print(
        f"Balanced Accuracy="
        f"{best_candidate['Balanced_Acc_Mean']:.4f}"
    )


    # --------------------------------------------------------
    # SAVE PROGRESS AFTER EVERY ITERATION
    # Important if Colab disconnects
    # --------------------------------------------------------

    progress_df = pd.DataFrame(
        e2_selection_history
    )

    progress_df.to_csv(
        f"{OUTPUT_DIR}/E2_backward_ablation_progress.csv",
        index=False
    )

    candidates_df = pd.DataFrame(
        e2_candidate_history
    )

    candidates_df.to_csv(
        f"{OUTPUT_DIR}/E2_backward_ablation_all_candidates.csv",
        index=False
    )

    print(
        f"Progress saved at "
        f"{len(current_features)} features."
    )


# ============================================================
# FINAL SELECTED PATH
# ============================================================

e2_df = pd.DataFrame(
    e2_selection_history
)

# Sort from 26 features down to 1
e2_df = e2_df.sort_values(
    "Num_Features",
    ascending=False
).reset_index(drop=True)


# ------------------------------------------------------------
# CREATE DISPLAY COLUMNS WITH MEAN ± SD
# ------------------------------------------------------------

for metric in metrics_to_collect:

    e2_df[metric] = e2_df.apply(
        lambda row:
            f"{row[f'{metric}_Mean']:.4f} ± "
            f"{row[f'{metric}_SD']:.4f}",
        axis=1
    )


# ------------------------------------------------------------
# SAVE FINAL RESULTS
# ------------------------------------------------------------

final_file = (
    f"{OUTPUT_DIR}/"
    "E2_sequential_backward_ablation.csv"
)

e2_df.to_csv(
    final_file,
    index=False
)


# ============================================================
# FIND BEST FEATURE SUBSET
# ============================================================

best_row_index = e2_df[
    "AUC_Macro_Mean"
].idxmax()

best_subset = e2_df.loc[
    best_row_index
]

print("\n" + "=" * 70)
print("EXPERIMENT 2 COMPLETE")
print("=" * 70)

print(
    e2_df[
        [
            "Num_Features",
            "Removed_Feature",
            "AUC_Macro",
            "Accuracy",
            "Balanced_Acc",
            "F1_Macro",
            "MCC",
            "LogLoss"
        ]
    ].to_string(index=False)
)


print("\n" + "-" * 70)
print("BEST FEATURE SUBSET")
print("-" * 70)

print(
    "Number of features:",
    int(best_subset["Num_Features"])
)

print(
    "Macro F1:",
    f"{best_subset['F1_Macro_Mean']:.4f}"
)

print(
    "Macro AUC:",
    f"{best_subset['AUC_Macro_Mean']:.4f}"
)

print(
    "\nRemaining features:"
)

for feature in best_subset[
    "Remaining_Features"
].split(" | "):

    print(" -", feature)


print(
    f"\n Final results saved: {final_file}"
)

print(
    f" All candidate subsets saved: "
    f"{OUTPUT_DIR}/E2_backward_ablation_all_candidates.csv"
)

print(
    f"Progress file saved: "
    f"{OUTPUT_DIR}/E2_backward_ablation_progress.csv"
)

======================================================================
EXPERIMENT 2: SEQUENTIAL BACKWARD FEATURE ABLATION
======================================================================
Starting number of features: 26
Stopping at: 1 features
Selection metric: AUC_Macro

----------------------------------------------------------------------
Evaluating FULL model with 26 features
----------------------------------------------------------------------
Full model: Macro F1=0.7571 | AUC=0.9022 | Balanced Acc=0.7580

======================================================================
Finding best 25-feature subset from current 26 features
======================================================================
[1/26] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7556 | AUC=0.9023
[2/26] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7552 | AUC=0.9005
[3/26] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7285 | AUC=0.8815
[4/26] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7344 | AUC=0.8911
[5/26] Testing removal of: MOCA_MOCA
    Macro F1=0.7497 | AUC=0.8954
[6/26] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7554 | AUC=0.9019
[7/26] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7547 | AUC=0.9020
[8/26] Testing removal of: AGE
    Macro F1=0.7522 | AUC=0.8999
[9/26] Testing removal of: APOERES_?4 Count
    Macro F1=0.7551 | AUC=0.9023
[10/26] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7550 | AUC=0.9021
[11/26] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7562 | AUC=0.9023
[12/26] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7544 | AUC=0.9023
[13/26] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7540 | AUC=0.9018
[14/26] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7565 | AUC=0.9021
[15/26] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7583 | AUC=0.9023
[16/26] Testing removal of: UCSFFSX7_ST12SV
    Macro F1=0.7584 | AUC=0.9026
[17/26] Testing removal of: UCSFFSX7_ST1SV
    Macro F1=0.7578 | AUC=0.9025
[18/26] Testing removal of: UCSFFSX7_ST16SV
    Macro F1=0.7565 | AUC=0.9027
[19/26] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7570 | AUC=0.9025
[20/26] Testing removal of: AMYLOID_SUMMARY_SUVR
    Macro F1=0.7549 | AUC=0.9023
[21/26] Testing removal of: AMYLOID_CENTILOIDS
    Macro F1=0.7541 | AUC=0.9023
[22/26] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7554 | AUC=0.9022
[23/26] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7574 | AUC=0.9024
[24/26] Testing removal of: AMYLOID_CTX_ENTORHINAL_SUVR
    Macro F1=0.7566 | AUC=0.9023
[25/26] Testing removal of: AMYLOID_CTX_PRECUNEUS_SUVR
    Macro F1=0.7539 | AUC=0.9023
[26/26] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7539 | AUC=0.9023

*** SELECTED REMOVAL ***
Removed: UCSFFSX7_ST16SV
Remaining features: 25
Macro F1=0.7565
Macro AUC=0.9027
Balanced Accuracy=0.7575
Progress saved at 25 features.

======================================================================
Finding best 24-feature subset from current 25 features
======================================================================
[1/25] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7555 | AUC=0.9024
[2/25] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7556 | AUC=0.9005
[3/25] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7303 | AUC=0.8817
[4/25] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7334 | AUC=0.8909
[5/25] Testing removal of: MOCA_MOCA
    Macro F1=0.7500 | AUC=0.8952
[6/25] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7564 | AUC=0.9015
[7/25] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7575 | AUC=0.9019
[8/25] Testing removal of: AGE
    Macro F1=0.7521 | AUC=0.8999
[9/25] Testing removal of: APOERES_?4 Count
    Macro F1=0.7567 | AUC=0.9022
[10/25] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7558 | AUC=0.9018
[11/25] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7574 | AUC=0.9021
[12/25] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7564 | AUC=0.9023
[13/25] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7516 | AUC=0.9016
[14/25] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7560 | AUC=0.9018
[15/25] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7579 | AUC=0.9021
[16/25] Testing removal of: UCSFFSX7_ST12SV
    Macro F1=0.7596 | AUC=0.9027
[17/25] Testing removal of: UCSFFSX7_ST1SV
    Macro F1=0.7541 | AUC=0.9023
[18/25] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7569 | AUC=0.9022
[19/25] Testing removal of: AMYLOID_SUMMARY_SUVR
    Macro F1=0.7578 | AUC=0.9021
[20/25] Testing removal of: AMYLOID_CENTILOIDS
    Macro F1=0.7586 | AUC=0.9023
[21/25] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7584 | AUC=0.9022
[22/25] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7567 | AUC=0.9019
[23/25] Testing removal of: AMYLOID_CTX_ENTORHINAL_SUVR
    Macro F1=0.7571 | AUC=0.9025
[24/25] Testing removal of: AMYLOID_CTX_PRECUNEUS_SUVR
    Macro F1=0.7599 | AUC=0.9030
[25/25] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7580 | AUC=0.9023

*** SELECTED REMOVAL ***
Removed: AMYLOID_CTX_PRECUNEUS_SUVR
Remaining features: 24
Macro F1=0.7599
Macro AUC=0.9030
Balanced Accuracy=0.7600
Progress saved at 24 features.

======================================================================
Finding best 23-feature subset from current 24 features
======================================================================
[1/24] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7572 | AUC=0.9024
[2/24] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7573 | AUC=0.9006
[3/24] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7318 | AUC=0.8817
[4/24] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7367 | AUC=0.8915
[5/24] Testing removal of: MOCA_MOCA
    Macro F1=0.7482 | AUC=0.8956
[6/24] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7568 | AUC=0.9020
[7/24] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7553 | AUC=0.9023
[8/24] Testing removal of: AGE
    Macro F1=0.7536 | AUC=0.9003
[9/24] Testing removal of: APOERES_?4 Count
    Macro F1=0.7540 | AUC=0.9026
[10/24] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7565 | AUC=0.9023
[11/24] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7575 | AUC=0.9024
[12/24] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7571 | AUC=0.9023
[13/24] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7524 | AUC=0.9019
[14/24] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7582 | AUC=0.9022
[15/24] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7576 | AUC=0.9023
[16/24] Testing removal of: UCSFFSX7_ST12SV
    Macro F1=0.7594 | AUC=0.9026
[17/24] Testing removal of: UCSFFSX7_ST1SV
    Macro F1=0.7577 | AUC=0.9025
[18/24] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7548 | AUC=0.9023
[19/24] Testing removal of: AMYLOID_SUMMARY_SUVR
    Macro F1=0.7566 | AUC=0.9027
[20/24] Testing removal of: AMYLOID_CENTILOIDS
    Macro F1=0.7580 | AUC=0.9023
[21/24] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7574 | AUC=0.9021
[22/24] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7572 | AUC=0.9021
[23/24] Testing removal of: AMYLOID_CTX_ENTORHINAL_SUVR
    Macro F1=0.7571 | AUC=0.9023
[24/24] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7604 | AUC=0.9026

*** SELECTED REMOVAL ***
Removed: AMYLOID_SUMMARY_SUVR
Remaining features: 23
Macro F1=0.7566
Macro AUC=0.9027
Balanced Accuracy=0.7573
Progress saved at 23 features.

======================================================================
Finding best 22-feature subset from current 23 features
======================================================================
[1/23] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7581 | AUC=0.9024
[2/23] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7563 | AUC=0.9008
[3/23] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7331 | AUC=0.8817
[4/23] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7351 | AUC=0.8913
[5/23] Testing removal of: MOCA_MOCA
    Macro F1=0.7477 | AUC=0.8955
[6/23] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7580 | AUC=0.9020
[7/23] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7544 | AUC=0.9025
[8/23] Testing removal of: AGE
    Macro F1=0.7528 | AUC=0.9003
[9/23] Testing removal of: APOERES_?4 Count
    Macro F1=0.7548 | AUC=0.9025
[10/23] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7551 | AUC=0.9022
[11/23] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7563 | AUC=0.9025
[12/23] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7563 | AUC=0.9024
[13/23] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7544 | AUC=0.9019
[14/23] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7558 | AUC=0.9023
[15/23] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7548 | AUC=0.9023
[16/23] Testing removal of: UCSFFSX7_ST12SV
    Macro F1=0.7583 | AUC=0.9025
[17/23] Testing removal of: UCSFFSX7_ST1SV
    Macro F1=0.7574 | AUC=0.9025
[18/23] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7591 | AUC=0.9025
[19/23] Testing removal of: AMYLOID_CENTILOIDS
    Macro F1=0.7570 | AUC=0.9021
[20/23] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7553 | AUC=0.9021
[21/23] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7564 | AUC=0.9023
[22/23] Testing removal of: AMYLOID_CTX_ENTORHINAL_SUVR
    Macro F1=0.7576 | AUC=0.9024
[23/23] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7553 | AUC=0.9023

*** SELECTED REMOVAL ***
Removed: UCSFFSX7_ST12SV
Remaining features: 22
Macro F1=0.7583
Macro AUC=0.9025
Balanced Accuracy=0.7588
Progress saved at 22 features.

======================================================================
Finding best 21-feature subset from current 22 features
======================================================================
[1/22] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7594 | AUC=0.9025
[2/22] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7572 | AUC=0.9009
[3/22] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7317 | AUC=0.8822
[4/22] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7363 | AUC=0.8915
[5/22] Testing removal of: MOCA_MOCA
    Macro F1=0.7476 | AUC=0.8960
[6/22] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7580 | AUC=0.9024
[7/22] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7572 | AUC=0.9025
[8/22] Testing removal of: AGE
    Macro F1=0.7548 | AUC=0.9004
[9/22] Testing removal of: APOERES_?4 Count
    Macro F1=0.7547 | AUC=0.9026
[10/22] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7549 | AUC=0.9023
[11/22] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7567 | AUC=0.9026
[12/22] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7562 | AUC=0.9025
[13/22] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7557 | AUC=0.9019
[14/22] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7582 | AUC=0.9021
[15/22] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7576 | AUC=0.9025
[16/22] Testing removal of: UCSFFSX7_ST1SV
    Macro F1=0.7568 | AUC=0.9026
[17/22] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7561 | AUC=0.9027
[18/22] Testing removal of: AMYLOID_CENTILOIDS
    Macro F1=0.7592 | AUC=0.9027
[19/22] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7553 | AUC=0.9024
[20/22] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7579 | AUC=0.9025
[21/22] Testing removal of: AMYLOID_CTX_ENTORHINAL_SUVR
    Macro F1=0.7579 | AUC=0.9025
[22/22] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7573 | AUC=0.9027

*** SELECTED REMOVAL ***
Removed: AMYLOID_CENTILOIDS
Remaining features: 21
Macro F1=0.7592
Macro AUC=0.9027
Balanced Accuracy=0.7601
Progress saved at 21 features.

======================================================================
Finding best 20-feature subset from current 21 features
======================================================================
[1/21] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7562 | AUC=0.9023
[2/21] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7568 | AUC=0.9008
[3/21] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7276 | AUC=0.8819
[4/21] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7348 | AUC=0.8913
[5/21] Testing removal of: MOCA_MOCA
    Macro F1=0.7483 | AUC=0.8959
[6/21] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7568 | AUC=0.9020
[7/21] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7603 | AUC=0.9025
[8/21] Testing removal of: AGE
    Macro F1=0.7528 | AUC=0.9001
[9/21] Testing removal of: APOERES_?4 Count
    Macro F1=0.7583 | AUC=0.9026
[10/21] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7592 | AUC=0.9024
[11/21] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7600 | AUC=0.9025
[12/21] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7595 | AUC=0.9025
[13/21] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7560 | AUC=0.9018
[14/21] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7586 | AUC=0.9025
[15/21] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7566 | AUC=0.9025
[16/21] Testing removal of: UCSFFSX7_ST1SV
    Macro F1=0.7569 | AUC=0.9027
[17/21] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7580 | AUC=0.9026
[18/21] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7571 | AUC=0.9025
[19/21] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7581 | AUC=0.9026
[20/21] Testing removal of: AMYLOID_CTX_ENTORHINAL_SUVR
    Macro F1=0.7558 | AUC=0.9027
[21/21] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7592 | AUC=0.9025

*** SELECTED REMOVAL ***
Removed: UCSFFSX7_ST1SV
Remaining features: 20
Macro F1=0.7569
Macro AUC=0.9027
Balanced Accuracy=0.7578
Progress saved at 20 features.

======================================================================
Finding best 19-feature subset from current 20 features
======================================================================
[1/20] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7551 | AUC=0.9021
[2/20] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7555 | AUC=0.9005
[3/20] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7306 | AUC=0.8815
[4/20] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7375 | AUC=0.8914
[5/20] Testing removal of: MOCA_MOCA
    Macro F1=0.7501 | AUC=0.8959
[6/20] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7564 | AUC=0.9019
[7/20] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7549 | AUC=0.9023
[8/20] Testing removal of: AGE
    Macro F1=0.7535 | AUC=0.9004
[9/20] Testing removal of: APOERES_?4 Count
    Macro F1=0.7578 | AUC=0.9027
[10/20] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7574 | AUC=0.9022
[11/20] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7580 | AUC=0.9026
[12/20] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7570 | AUC=0.9026
[13/20] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7562 | AUC=0.9018
[14/20] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7589 | AUC=0.9024
[15/20] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7613 | AUC=0.9025
[16/20] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7582 | AUC=0.9026
[17/20] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7575 | AUC=0.9023
[18/20] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7610 | AUC=0.9026
[19/20] Testing removal of: AMYLOID_CTX_ENTORHINAL_SUVR
    Macro F1=0.7578 | AUC=0.9027
[20/20] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7595 | AUC=0.9026

*** SELECTED REMOVAL ***
Removed: AMYLOID_CTX_ENTORHINAL_SUVR
Remaining features: 19
Macro F1=0.7578
Macro AUC=0.9027
Balanced Accuracy=0.7580
Progress saved at 19 features.

======================================================================
Finding best 18-feature subset from current 19 features
======================================================================
[1/19] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7581 | AUC=0.9023
[2/19] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7567 | AUC=0.9007
[3/19] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7267 | AUC=0.8817
[4/19] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7373 | AUC=0.8917
[5/19] Testing removal of: MOCA_MOCA
    Macro F1=0.7464 | AUC=0.8950
[6/19] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7572 | AUC=0.9019
[7/19] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7569 | AUC=0.9022
[8/19] Testing removal of: AGE
    Macro F1=0.7537 | AUC=0.8997
[9/19] Testing removal of: APOERES_?4 Count
    Macro F1=0.7551 | AUC=0.9024
[10/19] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7580 | AUC=0.9020
[11/19] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7571 | AUC=0.9022
[12/19] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7583 | AUC=0.9024
[13/19] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7536 | AUC=0.9016
[14/19] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7547 | AUC=0.9023
[15/19] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7559 | AUC=0.9021
[16/19] Testing removal of: UCSFFSX7_ST17SV
    Macro F1=0.7591 | AUC=0.9027
[17/19] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7578 | AUC=0.9021
[18/19] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7585 | AUC=0.9023
[19/19] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7594 | AUC=0.9024

*** SELECTED REMOVAL ***
Removed: UCSFFSX7_ST17SV
Remaining features: 18
Macro F1=0.7591
Macro AUC=0.9027
Balanced Accuracy=0.7594
Progress saved at 18 features.

======================================================================
Finding best 17-feature subset from current 18 features
======================================================================
[1/18] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7585 | AUC=0.9025
[2/18] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7558 | AUC=0.9008
[3/18] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7265 | AUC=0.8818
[4/18] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7369 | AUC=0.8912
[5/18] Testing removal of: MOCA_MOCA
    Macro F1=0.7479 | AUC=0.8949
[6/18] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7598 | AUC=0.9020
[7/18] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7591 | AUC=0.9022
[8/18] Testing removal of: AGE
    Macro F1=0.7559 | AUC=0.8999
[9/18] Testing removal of: APOERES_?4 Count
    Macro F1=0.7562 | AUC=0.9026
[10/18] Testing removal of: UPENNBIOMK_ABETA42
    Macro F1=0.7608 | AUC=0.9023
[11/18] Testing removal of: UPENNBIOMK_TAU
    Macro F1=0.7596 | AUC=0.9024
[12/18] Testing removal of: UPENNBIOMK_PTAU
    Macro F1=0.7600 | AUC=0.9026
[13/18] Testing removal of: UCSFFSX7_ST29SV
    Macro F1=0.7546 | AUC=0.9015
[14/18] Testing removal of: UCSFFSX7_ST30SV
    Macro F1=0.7570 | AUC=0.9024
[15/18] Testing removal of: UCSFFSX7_ST11SV
    Macro F1=0.7584 | AUC=0.9025
[16/18] Testing removal of: AMYLOID_COMPOSITE_REF_SUVR
    Macro F1=0.7596 | AUC=0.9022
[17/18] Testing removal of: AMYLOID_HIPPOCAMPUS_SUVR
    Macro F1=0.7592 | AUC=0.9023
[18/18] Testing removal of: AMYLOID_CTX_POSTERIORCINGULATE_SUVR
    Macro F1=0.7602 | AUC=0.9026

*** SELECTED REMOVAL ***
Removed: UPENNBIOMK_PTAU
Remaining features: 17
Macro F1=0.7600
Macro AUC=0.9026
Balanced Accuracy=0.7606
Progress saved at 17 features.

======================================================================
Finding best 16-feature subset from current 17 features
======================================================================
[1/17] Testing removal of: ADAS_TOTSCORE
    Macro F1=0.7581 | AUC=0.9025
[2/17] Testing removal of: ADAS_TOTAL13
    Macro F1=0.7566 | AUC=0.9008
[3/17] Testing removal of: FAQ_FAQTOTAL
    Macro F1=0.7259 | AUC=0.8817
[4/17] Testing removal of: MMSE_MMSCORE
    Macro F1=0.7377 | AUC=0.8915
[5/17] Testing removal of: MOCA_MOCA
    Macro F1=0.7496 | AUC=0.8949
[6/17] Testing removal of: PTDEMOG_PTGENDER
    Macro F1=0.7607 | AUC=0.9022
[7/17] Testing removal of: PTDEMOG_PTEDUCAT
    Macro F1=0.7586 | AUC=0.9026
[8/17] Testing removal of: AGE

In [ ]:
# ============================================================
# TOP 5 FEATURE SUBSETS BY MACRO AUC
# ============================================================

top5_subsets = (
    e2_df
    .sort_values("AUC_Macro_Mean", ascending=False)
    .head(5)
    .copy()
)

top5_subsets["Rank"] = range(1, len(top5_subsets) + 1)

top5_subsets = top5_subsets[
    [
        "Rank",
        "Num_Features",
        "Removed_Feature",
        "AUC_Macro",
        "Accuracy",
        "Balanced_Acc",
        "F1_Macro",
        "MCC",
        "LogLoss",
        "Remaining_Features"
    ]
]

print("\n" + "=" * 70)
print("TOP 5 FEATURE SUBSETS BY MACRO AUC")
print("=" * 70)

for _, row in top5_subsets.iterrows():

    print(f"\nRank {int(row['Rank'])}")
    print(f"Number of retained features: {int(row['Num_Features'])}")
    print(f"AUC: {row['AUC_Macro']}")
    print(f"Accuracy: {row['Accuracy']}")
    print(f"F1-Macro: {row['F1_Macro']}")
    print(f"MCC: {row['MCC']}")

    print("\nRetained features:")

    retained = row["Remaining_Features"].split(" | ")

    for feature in retained:
        print(" -", feature)

    print("-" * 70)


# Save top 5
top5_subsets.to_csv(
    f"{OUTPUT_DIR}/E2_top5_feature_subsets.csv",
    index=False
)

print(
    f"\n Saved: "
    f"{OUTPUT_DIR}/E2_top5_feature_subsets.csv"
)

======================================================================
TOP 5 FEATURE SUBSETS BY MACRO AUC
======================================================================

Rank 1
Number of retained features: 15
AUC: 0.9030 ± 0.0098
Accuracy: 0.7624 ± 0.0150
F1-Macro: 0.7602 ± 0.0157
MCC: 0.6393 ± 0.0235

Retained features:
 - ADAS_TOTSCORE
 - ADAS_TOTAL13
 - FAQ_FAQTOTAL
 - MMSE_MMSCORE
 - MOCA_MOCA
 - PTDEMOG_PTGENDER
 - PTDEMOG_PTEDUCAT
 - AGE
 - UPENNBIOMK_ABETA42
 - UPENNBIOMK_TAU
 - UCSFFSX7_ST29SV
 - UCSFFSX7_ST30SV
 - UCSFFSX7_ST11SV
 - AMYLOID_COMPOSITE_REF_SUVR
 - AMYLOID_CTX_POSTERIORCINGULATE_SUVR
----------------------------------------------------------------------

Rank 2
Number of retained features: 24
AUC: 0.9030 ± 0.0095
Accuracy: 0.7622 ± 0.0148
F1-Macro: 0.7599 ± 0.0155
MCC: 0.6387 ± 0.0232

Retained features:
 - ADAS_TOTSCORE
 - ADAS_TOTAL13
 - FAQ_FAQTOTAL
 - MMSE_MMSCORE
 - MOCA_MOCA
 - PTDEMOG_PTGENDER
 - PTDEMOG_PTEDUCAT
 - AGE
 - APOERES_?4 Count
 - UPENNBIOMK_ABETA42
 - UPENNBIOMK_TAU
 - UPENNBIOMK_PTAU
 - UCSFFSX7_ST29SV
 - UCSFFSX7_ST30SV
 - UCSFFSX7_ST11SV
 - UCSFFSX7_ST12SV
 - UCSFFSX7_ST1SV
 - UCSFFSX7_ST17SV
 - AMYLOID_SUMMARY_SUVR
 - AMYLOID_CENTILOIDS
 - AMYLOID_COMPOSITE_REF_SUVR
 - AMYLOID_HIPPOCAMPUS_SUVR
 - AMYLOID_CTX_ENTORHINAL_SUVR
 - AMYLOID_CTX_POSTERIORCINGULATE_SUVR
----------------------------------------------------------------------

Rank 3
Number of retained features: 14
AUC: 0.9028 ± 0.0100
Accuracy: 0.7632 ± 0.0123
F1-Macro: 0.7616 ± 0.0134
MCC: 0.6401 ± 0.0192

Retained features:
 - ADAS_TOTSCORE
 - ADAS_TOTAL13
 - FAQ_FAQTOTAL
 - MMSE_MMSCORE
 - MOCA_MOCA
 - PTDEMOG_PTGENDER
 - PTDEMOG_PTEDUCAT
 - AGE
 - UPENNBIOMK_ABETA42
 - UPENNBIOMK_TAU
 - UCSFFSX7_ST29SV
 - UCSFFSX7_ST30SV
 - AMYLOID_COMPOSITE_REF_SUVR
 - AMYLOID_CTX_POSTERIORCINGULATE_SUVR
----------------------------------------------------------------------

Rank 4
Number of retained features: 16
AUC: 0.9028 ± 0.0099
Accuracy: 0.7614 ± 0.0174
F1-Macro: 0.7591 ± 0.0187
MCC: 0.6375 ± 0.0270

Retained features:
 - ADAS_TOTSCORE
 - ADAS_TOTAL13
 - FAQ_FAQTOTAL
 - MMSE_MMSCORE
 - MOCA_MOCA
 - PTDEMOG_PTGENDER
 - PTDEMOG_PTEDUCAT
 - AGE
 - UPENNBIOMK_ABETA42
 - UPENNBIOMK_TAU
 - UCSFFSX7_ST29SV
 - UCSFFSX7_ST30SV
 - UCSFFSX7_ST11SV
 - AMYLOID_COMPOSITE_REF_SUVR
 - AMYLOID_HIPPOCAMPUS_SUVR
 - AMYLOID_CTX_POSTERIORCINGULATE_SUVR
----------------------------------------------------------------------

Rank 5
Number of retained features: 18
AUC: 0.9027 ± 0.0099
Accuracy: 0.7614 ± 0.0169
F1-Macro: 0.7591 ± 0.0176
MCC: 0.6375 ± 0.0264

Retained features:
 - ADAS_TOTSCORE
 - ADAS_TOTAL13
 - FAQ_FAQTOTAL
 - MMSE_MMSCORE
 - MOCA_MOCA
 - PTDEMOG_PTGENDER
 - PTDEMOG_PTEDUCAT
 - AGE
 - APOERES_?4 Count
 - UPENNBIOMK_ABETA42
 - UPENNBIOMK_TAU
 - UPENNBIOMK_PTAU
 - UCSFFSX7_ST29SV
 - UCSFFSX7_ST30SV
 - UCSFFSX7_ST11SV
 - AMYLOID_COMPOSITE_REF_SUVR
 - AMYLOID_HIPPOCAMPUS_SUVR
 - AMYLOID_CTX_POSTERIORCINGULATE_SUVR
----------------------------------------------------------------------

✅ Saved: ADNI results/E2_top5_feature_subsets.csv

In [ ]:
def format_features_for_display(feature_str):
    if pd.isna(feature_str): return ""
    features = feature_str.split(' | ')
    # Use FEATURE_LABELS for human-readable names, fall back to original if not found
    display_features = [FEATURE_LABELS.get(f, f) for f in features]
    return ", ".join(display_features)

# Apply the formatting to the 'Remaining_Features' column
top5_subsets_display = top5_subsets.copy()
top5_subsets_display['Remaining_Features_Display'] = top5_subsets_display['Remaining_Features'].apply(format_features_for_display)

# Select and reorder columns for journal presentation
journal_table = top5_subsets_display[[
    'Rank',
    'Num_Features',
    'AUC_Macro',
    'F1_Macro',
    'Accuracy',
    'Balanced_Acc',
    'MCC',
    'Remaining_Features_Display'
]].rename(columns={
    'Rank': 'Rank',
    'Num_Features': 'Features',
    'AUC_Macro': 'AUC (Macro)',
    'F1_Macro': 'F1 (Macro)',
    'Accuracy': 'Accuracy',
    'Balanced_Acc': 'Balanced Accuracy',
    'MCC': 'MCC',
    'Remaining_Features_Display': 'Retained Features'
})

print("\n" + "=" * 80)
print("TABLE 1: TOP 5 FEATURE SUBSETS BY MACRO AUC (Journal Format)")
print("=" * 80)
print(journal_table.to_markdown(index=False))

# Save this formatted table to a new CSV for journal export
journal_table.to_csv(f"{OUTPUT_DIR}/E2_top5_feature_subsets_journal.csv", index=False)
print(f"\n Saved journal-formatted table to: {OUTPUT_DIR}/E2_top5_feature_subsets_journal.csv")

================================================================================
TABLE 1: TOP 5 FEATURE SUBSETS BY MACRO AUC (Journal Format)
================================================================================
|   Rank |   Features | AUC (Macro)     | F1 (Macro)      | Accuracy        | Balanced Accuracy   | MCC             | Retained Features                                                                                                                                                                                                                                                                                                         |
|-------:|-----------:|:----------------|:----------------|:----------------|:--------------------|:----------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|      1 |         15 | 0.9030 ± 0.0098 | 0.7602 ± 0.0157 | 0.7624 ± 0.0150 | 0.7609 ± 0.0158     | 0.6393 ± 0.0235 | ADAS-Cog 11, ADAS-Cog 13, FAQ, MMSE, MoCA, Sex, Education, AGE, CSF Aβ42, CSF Total-tau, Hippocampus L, Hippocampus R, Entorhinal L, Composite SUVR, Amyloid Post. Cingulate                                                                                                                                              |
|      2 |         24 | 0.9030 ± 0.0095 | 0.7599 ± 0.0155 | 0.7622 ± 0.0148 | 0.7600 ± 0.0160     | 0.6387 ± 0.0232 | ADAS-Cog 11, ADAS-Cog 13, FAQ, MMSE, MoCA, Sex, Education, AGE, APOE ε4 count, CSF Aβ42, CSF Total-tau, CSF p-tau 181, Hippocampus L, Hippocampus R, Entorhinal L, Entorhinal R, ICV, Lat. Ventricle R, Amyloid Global SUVR, Centiloids, Composite SUVR, Amyloid Hippocampus, Amyloid Entorhinal, Amyloid Post. Cingulate |
|      3 |         14 | 0.9028 ± 0.0100 | 0.7616 ± 0.0134 | 0.7632 ± 0.0123 | 0.7619 ± 0.0136     | 0.6401 ± 0.0192 | ADAS-Cog 11, ADAS-Cog 13, FAQ, MMSE, MoCA, Sex, Education, AGE, CSF Aβ42, CSF Total-tau, Hippocampus L, Hippocampus R, Composite SUVR, Amyloid Post. Cingulate                                                                                                                                                            |
|      4 |         16 | 0.9028 ± 0.0099 | 0.7591 ± 0.0187 | 0.7614 ± 0.0174 | 0.7597 ± 0.0186     | 0.6375 ± 0.0270 | ADAS-Cog 11, ADAS-Cog 13, FAQ, MMSE, MoCA, Sex, Education, AGE, CSF Aβ42, CSF Total-tau, Hippocampus L, Hippocampus R, Entorhinal L, Composite SUVR, Amyloid Hippocampus, Amyloid Post. Cingulate                                                                                                                         |
|      5 |         18 | 0.9027 ± 0.0099 | 0.7591 ± 0.0176 | 0.7614 ± 0.0169 | 0.7594 ± 0.0180     | 0.6375 ± 0.0264 | ADAS-Cog 11, ADAS-Cog 13, FAQ, MMSE, MoCA, Sex, Education, AGE, APOE ε4 count, CSF Aβ42, CSF Total-tau, CSF p-tau 181, Hippocampus L, Hippocampus R, Entorhinal L, Composite SUVR, Amyloid Hippocampus, Amyloid Post. Cingulate                                                                                           |

✅ Saved journal-formatted table to: ADNI results/E2_top5_feature_subsets_journal.csv

##  Experiment 3: Data Efficiency
Train on 10%, 25%, 50%, 75%, 100% of data. Shows TabPFN v3.0 advantage in low-data regimes.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
import shutil # Import shutil for AutoGluon directory cleanup
from autogluon.tabular import TabularPredictor # Import TabularPredictor
import tempfile # Import tempfile for temporary directories

# Ensure train/test split exists
try:
    X_train, X_test, y_train, y_test
except NameError:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_SEED
    )

PROPORTIONS = [0.10, 0.25, 0.50, 0.75, 1.00]
e3_rows = []

print("Running Experiment 3: Data Efficiency...")
for prop in PROPORTIONS:
    if prop < 1.0:
        Xtr, _, ytr, _ = train_test_split(
            X_train, y_train, train_size=prop, stratify=y_train, random_state=RANDOM_SEED
        )
    else:
        Xtr, ytr = X_train, y_train

    # Prepare Xtr and Xte for models that need imputation vs. raw
    Xtr_imputed, Xte_imputed = median_impute(Xtr, X_test)
    Xtr_raw, Xte_raw = Xtr.copy(), X_test.copy()

    for name, model_info in [
        ('TabPFN', {'model_func': get_tabpfn, 'Xtr': Xtr_raw, 'Xte': Xte_raw}),
        ('XGBoost', {'model_func': lambda: XGBClassifier(n_estimators=1000, random_state=RANDOM_SEED, eval_metric='mlogloss', n_jobs=N_JOBS), 'Xtr': Xtr_imputed, 'Xte': Xte_imputed}),
        ('AutoGluon', {'model_func': lambda path: TabularPredictor(label="label", problem_type="multiclass", eval_metric="accuracy", path=path, verbosity=0), 'Xtr': Xtr_raw, 'Xte': Xte_raw})
    ]:
        clf = None # Initialize clf outside try-except
        temp_path = None # Initialize temp_path
        try:
            if name == 'AutoGluon':
                # Create a temporary directory for AutoGluon models for this run
                temp_path = tempfile.mkdtemp()
                clf = model_info['model_func'](temp_path)
                # AutoGluon needs train_data as a DataFrame with the label column
                train_data_ag = model_info['Xtr'].copy()
                train_data_ag['label'] = model_info['ytr'] if 'ytr' in model_info else ytr.copy()
                clf.fit(train_data=train_data_ag, presets="medium_quality", num_gpus=0)
                X_fit_ag = model_info['Xte'].copy()
                pred = clf.predict(X_fit_ag).to_numpy(dtype=int)
                proba = align_probabilities(clf.predict_proba(X_fit_ag).to_numpy(), clf.class_labels)
            else:
                clf = model_info['model_func']()
                clf.fit(model_info['Xtr'], ytr)
                pred = clf.predict(model_info['Xte'])
                proba = align_probabilities(clf.predict_proba(model_info['Xte']), clf.classes_)

            m = compute_metrics(y_test, pred, proba)
            e3_rows.append({'Proportion': f"{int(prop*100)}%", 'Model': name, **m})

        except Exception as e:
            print(f"  - Error running {name} for {int(prop*100)}% proportion: {e}")
        finally:
            # Clean up AutoGluon temporary directory if created
            if temp_path and os.path.exists(temp_path):
                shutil.rmtree(temp_path)

    print(f"  - Completed {int(prop*100)}% sub-sampling")

e3_df = pd.DataFrame(e3_rows)
e3_df.to_csv(f'{OUTPUT_DIR}/E3_data_efficiency.csv', index=False)

# Plotting results with requested labels
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
metrics_mapping = {
    'AUC_Macro': 'Macro ROC-AUC',
    'F1_Macro': 'Macro F1-score',
    'Balanced_Acc': 'Balanced Accuracy'
}

for i, (orig_key, display_name) in enumerate(metrics_mapping.items()):
    sns.lineplot(data=e3_df, x='Proportion', y=orig_key, hue='Model', ax=axes[i], marker='o')
    axes[i].set_title(f'{display_name} vs Data %', fontweight='bold')
    axes[i].set_xlabel('Training Data Proportion')
    axes[i].set_ylabel(display_name)
    axes[i].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/figures/E3_data_efficiency.png')
plt.show()

Running Experiment 3: Data Efficiency...
  - Completed 10% sub-sampling
  - Completed 25% sub-sampling
  - Completed 50% sub-sampling
  - Completed 75% sub-sampling
  - Completed 100% sub-sampling

In [ ]:
import os
os.makedirs(f"{OUTPUT_DIR}/figures", exist_ok=True)

##  Experiment 4: Calibration Analysis
Evaluate how well each model's predicted probabilities match true outcomes.  
Metrics: **Brier Score** (lower = better) + **Reliability Diagrams**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.calibration import calibration_curve
from xgboost import XGBClassifier
import shutil # Import shutil for AutoGluon directory cleanup
from autogluon.tabular import TabularPredictor # Import TabularPredictor
import tempfile # Import tempfile for temporary directories

print('=' * 55)
print('EXPERIMENT 4: CALIBRATION ANALYSIS')
print('=' * 55)

def compute_per_class_ece(y_true_bin, y_proba_class, n_bins=10):
    bin_boundaries = np.linspace(0, 1, n_bins + 1)
    bin_lowers = bin_boundaries[:-1]
    bin_uppers = bin_boundaries[1:]
    ece = 0.0
    for bin_lower, bin_upper in zip(bin_lowers, bin_uppers):
        in_bin = (y_proba_class > bin_lower) & (y_proba_class <= bin_upper)
        prop_in_bin = np.mean(in_bin)
        if prop_in_bin > 0:
            accuracy_in_bin = np.mean(y_true_bin[in_bin])
            avg_confidence_in_bin = np.mean(y_proba_class[in_bin])
            ece += np.abs(avg_confidence_in_bin - accuracy_in_bin) * prop_in_bin
    return ece

# Ensure training data and helpers are available
try:
    Xtr_i, Xte_i = median_impute(X_train, X_test)
except NameError:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, stratify=y, random_state=RANDOM_SEED)
    Xtr_i, Xte_i = median_impute(X_train, X_test)

# For AutoGluon, use raw X_train, X_test as it handles its own preprocessing
Xtr_ag, Xte_ag = X_train.copy(), X_test.copy()

models_cal = {
    'FRAME-AD (TabPFN)': {'model_func': get_tabpfn, 'Xtr': X_train, 'Xte': X_test},
    'XGBoost': {'model_func': lambda: XGBClassifier(n_estimators=200, random_state=RANDOM_SEED, n_jobs=N_JOBS), 'Xtr': Xtr_i, 'Xte': Xte_i},
    'AutoGluon': {'model_func': lambda path: TabularPredictor(label="label", problem_type="multiclass", eval_metric="accuracy", path=path, verbosity=0), 'Xtr': Xtr_ag, 'Xte': Xte_ag}
}

e4_rows = []
all_probas = {}
# Initialize e4_results as a dictionary for the summary cell
e4_results = {}

for name, model_info in models_cal.items():
    print(f'  Fitting {name}...')
    clf = None
    temp_path = None # Initialize temp_path
    try:
        if name == 'AutoGluon':
            temp_path = tempfile.mkdtemp() # Create a temporary directory
            clf = model_info['model_func'](temp_path)
            train_data_ag = model_info['Xtr'].copy()
            train_data_ag['label'] = y_train.copy()
            clf.fit(train_data=train_data_ag, presets="medium_quality", num_gpus=0)
            X_fit_ag = model_info['Xte'].copy()
            pred = clf.predict(X_fit_ag).to_numpy(dtype=int)
            proba = align_probabilities(clf.predict_proba(X_fit_ag).to_numpy(), clf.class_labels)
        else:
            clf = model_info['model_func']()
            clf.fit(model_info['Xtr'], y_train)
            pred = clf.predict(model_info['Xte'])
            proba = align_probabilities(clf.predict_proba(model_info['Xte']), clf.classes_)

        all_probas[name] = proba
        metrics = compute_metrics(y_test, pred, proba)

        # Calculate Per-class ECE (OvR)
        y_test_bin = label_binarize(y_test, classes=[0, 1, 2])
        ece_cn = compute_per_class_ece(y_test_bin[:, 0], proba[:, 0])
        ece_mci = compute_per_class_ece(y_test_bin[:, 1], proba[:, 1])
        ece_ad = compute_per_class_ece(y_test_bin[:, 2], proba[:, 2])

        # Append to e4_rows for the dataframe
        e4_rows.append({
            'Model': name,
            'AUC_Macro': metrics['AUC_Macro'],
            'Accuracy': metrics['Accuracy'],
            'Balanced_Acc': metrics['Balanced_Acc'],
            'Macro_F1': metrics['F1_Macro'],
            'Brier': metrics['Brier'],
            'LogLoss': metrics['LogLoss'],
            'ECE_Overall': metrics['ECE'],
            'ECE_CN': ece_cn,
            'ECE_MCI': ece_mci,
            'ECE_AD': ece_ad
        })

        # Populate e4_results dictionary for the summary table in dWUu2WajgooB
        e4_results[name] = {
            'AUC_Macro': metrics['AUC_Macro'],
            'Accuracy': metrics['Accuracy'],
            'Brier': metrics['Brier']
        }
    except Exception as e:
        print(f"  - Error running {name} for calibration analysis: {e}")
    finally:
        # Clean up AutoGluon temporary directory if created
        if temp_path and os.path.exists(temp_path):
            shutil.rmtree(temp_path)

e4_df = pd.DataFrame(e4_rows)
e4_df.to_csv(f'{OUTPUT_DIR}/E4_calibration.csv', index=False)
display(e4_df)

# Reliability Diagrams
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
class_names = ['CN', 'MCI', 'AD']
colors = {'FRAME-AD (TabPFN)': '#E11D48', 'XGBoost': '#0D1B40', 'AutoGluon': '#8A2BE2'} # Add a color for AutoGluon

for i, cname in enumerate(class_names):
    y_true_c = (y_test == i).astype(int)
    axes[i].plot([0, 1], [0, 1], '--', color='gray', label='Perfectly Calibrated')

    for name in models_cal.keys():
        if name in all_probas: # Ensure probabilities were successfully generated
            prob_c = all_probas[name][:, i]
            fraction_of_positives, mean_predicted_value = calibration_curve(y_true_c, prob_c, n_bins=10)
            axes[i].plot(mean_predicted_value, fraction_of_positives, 's-', label=name, color=colors.get(name, 'black')) # Use .get for robustness

    axes[i].set_title(f'Reliability Diagram: {cname}', fontweight='bold')
    axes[i].set_xlabel('Mean Predicted Probability')
    axes[i].set_ylabel('Fraction of Positives')
    axes[i].legend(loc='lower right')
    axes[i].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(f'{OUTPUT_DIR}/figures/E4_reliability_diagrams.png')
plt.show()

=======================================================
EXPERIMENT 4: CALIBRATION ANALYSIS
=======================================================
  Fitting FRAME-AD (TabPFN)...
  Fitting XGBoost...
  Fitting AutoGluon...

,Model,AUC_Macro,Accuracy,Balanced_Acc,Macro_F1,Brier,LogLoss,ECE_Overall,ECE_CN,ECE_MCI,ECE_AD
0,FRAME-AD (TabPFN),0.907473,0.756757,0.756842,0.752255,0.108800,0.524411,0.038272,0.036610,0.050455,0.020048
1,XGBoost,0.887164,0.739189,0.741261,0.735801,0.134896,0.776506,0.145477,0.095834,0.144737,0.063620
2,AutoGluon,0.900974,0.754054,0.754375,0.748066,0.111441,0.542456,0.019054,0.034576,0.023752,0.020460

In [ ]:
import shutil
import os

# Define the name of the folder to zip and the output filename
folder_to_zip = OUTPUT_DIR # Already defined as 'ADNI results'
output_filename = 'frame_ad_results_after_exp4'

if os.path.exists(folder_to_zip):
    shutil.make_archive(output_filename, 'zip', folder_to_zip)
    print(f"✅ Successfully created {output_filename}.zip. You can download it from the file browser.")
else:
    print(f"❌ Error: The folder '{folder_to_zip}' was not found.")

✅ Successfully created frame_ad_results_after_exp4.zip. You can download it from the file browser.

## Experiment 5: SHAP Disease Insights — Setup
Fit final FRAME-AD model and compute SHAP values.

In [ ]:
import shap
import pandas as pd # Import pandas for DataFrame operations

print("=" * 55)
print("EXPERIMENT 5: SHAP DISEASE INSIGHTS")
print("=" * 55)

# Fit final TabPFN model on full training set
clf_shap = get_tabpfn()
clf_shap.fit(X_train, y_train)
print(" TabPFN fitted on training set")

# Sample test instances for SHAP (150 for speed, increase for more coverage)
N_SHAP_SAMPLES = 150
Xshap = X_test.sample(min(N_SHAP_SAMPLES, len(X_test)), random_state=RANDOM_SEED)
yshap = y_test.loc[Xshap.index]
print(f" SHAP sample: {len(Xshap)} test instances")

# Background dataset (100 training samples for KernelExplainer)
background = shap.sample(X_train, 100, random_state=RANDOM_SEED)
# Ensure the background dataset retains the original column names
background.columns = X_train.columns

# Define a wrapper function to ensure DataFrame input with column names and explicit dtypes for predict_proba
def model_predict_wrapper(X_data):
    # X_data might be a numpy array from shap, convert it back to DataFrame
    # Use X_train.columns as reference for the original feature names
    # Explicitly cast to float32, as models often expect this numeric type
    X_df = pd.DataFrame(X_data, columns=X_train.columns, dtype=np.float32)
    return clf_shap.predict_proba(X_df)

# KernelExplainer — model-agnostic, works with any classifier
print("\n  Computing SHAP values via KernelExplainer...")
print("  (nsamples=100 per instance — increase for more accuracy)")
# Pass the wrapper function to KernelExplainer
explainer   = shap.KernelExplainer(model_predict_wrapper, background)
shap_values = explainer.shap_values(Xshap, nsamples=100)
# shap_values = list of 3 arrays, one per class [n_samples x n_features]

print("\n SHAP computation complete")
print(f"   Classes     : {len(shap_values)}")
print(f"   Samples     : {shap_values[0].shape[0]}")
print(f"   Features    : {shap_values[0].shape[1]}")

# Rename for readable plots
Xshap_named = Xshap.rename(columns=FEATURE_LABELS)

=======================================================
EXPERIMENT 5: SHAP DISEASE INSIGHTS
=======================================================
 TabPFN fitted on training set
 SHAP sample: 150 test instances

  Computing SHAP values via KernelExplainer...
  (nsamples=100 per instance — increase for more accuracy)

  0%|          | 0/150 [00:00<?, ?it/s]

 SHAP computation complete
   Classes     : 150
   Samples     : 26
   Features    : 3

In [ ]:
print("Plotting 5a: Global SHAP per class...")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# CHECK AND STANDARDIZE SHAP VALUES
# ------------------------------------------------------------

feat_names = list(Xshap.columns)
class_names = ["CN", "MCI", "AD"]
colors_bar = ["#028090", "#0D1B40", "#E11D48"]

print("Number of features:", len(feat_names))
print("Type of shap_values:", type(shap_values))

if isinstance(shap_values, list):
    print("SHAP returned a list.")
    print("Number of class arrays:", len(shap_values))

    for i, values in enumerate(shap_values):
        print(f"Class {i} shape:", np.asarray(values).shape)

    # Expected format:
    # list of 3 arrays, each shaped:
    # (n_samples, n_features)
    shap_by_class = [
        np.asarray(values)
        for values in shap_values
    ]

else:
    shap_array = np.asarray(shap_values)

    print("SHAP array shape:", shap_array.shape)

    if shap_array.ndim != 3:
        raise ValueError(
            "Expected multiclass SHAP values to have three dimensions, "
            f"but received shape {shap_array.shape}."
        )

    n_samples = len(Xshap)
    n_features = Xshap.shape[1]
    n_classes = len(class_names)

    # Most recent SHAP format:
    # (samples, features, classes)
    if shap_array.shape == (
        n_samples,
        n_features,
        n_classes
    ):
        shap_by_class = [
            shap_array[:, :, class_index]
            for class_index in range(n_classes)
        ]

    # Alternative format:
    # (classes, samples, features)
    elif shap_array.shape == (
        n_classes,
        n_samples,
        n_features
    ):
        shap_by_class = [
            shap_array[class_index, :, :]
            for class_index in range(n_classes)
        ]

    # Alternative format:
    # (samples, classes, features)
    elif shap_array.shape == (
        n_samples,
        n_classes,
        n_features
    ):
        shap_by_class = [
            shap_array[:, class_index, :]
            for class_index in range(n_classes)
        ]

    else:
        raise ValueError(
            "Could not identify the SHAP dimension order.\n"
            f"SHAP shape: {shap_array.shape}\n"
            f"Expected samples: {n_samples}\n"
            f"Expected features: {n_features}\n"
            f"Expected classes: {n_classes}"
        )


# ------------------------------------------------------------
# VALIDATE EACH CLASS ARRAY
# ------------------------------------------------------------

for class_index, values in enumerate(shap_by_class):
    values = np.asarray(values)

    print(
        f"{class_names[class_index]} standardized shape:",
        values.shape
    )

    if values.ndim != 2:
        raise ValueError(
            f"{class_names[class_index]} SHAP values must be 2D, "
            f"but received shape {values.shape}."
        )

    if values.shape[1] != len(feat_names):
        raise ValueError(
            f"Feature mismatch for {class_names[class_index]}.\n"
            f"Xshap contains {len(feat_names)} features, but the "
            f"SHAP array contains {values.shape[1]} features."
        )


# ------------------------------------------------------------
# PLOT GLOBAL IMPORTANCE BY CLASS
# ------------------------------------------------------------

fig, axes = plt.subplots(
    1,
    3,
    figsize=(18, 7)
)

for class_index, (
    class_name,
    axis,
    color
) in enumerate(
    zip(
        class_names,
        axes,
        colors_bar
    )
):
    class_shap_values = shap_by_class[class_index]

    mean_absolute_shap = np.abs(
        class_shap_values
    ).mean(axis=0)

    top_feature_indices = np.argsort(
        mean_absolute_shap
    )[-15:]

    axis.barh(
        [feat_names[index] for index in top_feature_indices],
        mean_absolute_shap[top_feature_indices],
        color=color,
        alpha=0.85,
        edgecolor="white"
    )

    axis.set_title(
        f"Feature Importance — {class_name} Class",
        fontweight="bold",
        fontsize=12
    )

    axis.set_xlabel(
        "Mean |SHAP Value|",
        fontsize=10
    )

    axis.grid(
        axis="x",
        alpha=0.3
    )

    axis.spines["top"].set_visible(False)
    axis.spines["right"].set_visible(False)


plt.suptitle(
    "FRAME-AD: Global SHAP Feature Importance by Diagnostic Class",
    fontsize=14,
    fontweight="bold",
    y=1.02
)

plt.tight_layout()

plt.savefig(
    f"{OUTPUT_DIR}/figures/E5a_shap_global.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# CALCULATE IMPORTANCE PER CLASS
# ------------------------------------------------------------

mean_abs_per_class = []

for class_index, class_name in enumerate(class_names):
    class_mean_absolute_shap = np.abs(
        shap_by_class[class_index]
    ).mean(axis=0)

    mean_abs_per_class.append(
        class_mean_absolute_shap
    )


# Shape should now be:
# (3 classes, number of features)
mean_abs_per_class_stacked = np.vstack(
    mean_abs_per_class
)

print(
    "Stacked class importance shape:",
    mean_abs_per_class_stacked.shape
)


# Average importance across CN, MCI and AD
mean_abs_all = mean_abs_per_class_stacked.mean(
    axis=0
)

print(
    "Number of feature names:",
    len(feat_names)
)

print(
    "Number of overall SHAP values:",
    len(mean_abs_all)
)

if len(feat_names) != len(mean_abs_all):
    raise ValueError(
        "Feature names and SHAP importance values still do not match.\n"
        f"Feature names: {len(feat_names)}\n"
        f"SHAP values: {len(mean_abs_all)}"
    )


# ------------------------------------------------------------
# SAVE GLOBAL IMPORTANCE TABLE
# ------------------------------------------------------------

importance_data = {
    "Feature": feat_names,
    "Mean_SHAP": mean_abs_all
}

# Add class-specific importance columns
for class_index, class_name in enumerate(class_names):
    importance_data[
        f"Mean_SHAP_{class_name}"
    ] = mean_abs_per_class_stacked[
        class_index
    ]

imp_df = pd.DataFrame(
    importance_data
).sort_values(
    "Mean_SHAP",
    ascending=False
)

imp_df.to_csv(
    f"{OUTPUT_DIR}/E5_shap_importance_global.csv",
    index=False
)


# ------------------------------------------------------------
# SAVE RAW SHAP VALUES FOR EACH CLASS
# ------------------------------------------------------------

for class_index, class_name in enumerate(class_names):
    class_shap_dataframe = pd.DataFrame(
        shap_by_class[class_index],
        columns=feat_names
    )

    class_shap_dataframe.to_csv(
        f"{OUTPUT_DIR}/E5_shap_values_{class_name}.csv",
        index=False
    )


# Replace original shap_values with standardized list
# This allows your later subgroup cells to continue using:
# shap_values[class_index]
shap_values = shap_by_class


print(
    f"\n✅ Figure: "
    f"{OUTPUT_DIR}/figures/E5a_shap_global.png"
)

print(
    f"✅ Importance table: "
    f"{OUTPUT_DIR}/E5_shap_importance_global.csv"
)

print("\nTop 10 features across all classes:")

print(
    imp_df[
        [
            "Feature",
            "Mean_SHAP",
            "Mean_SHAP_CN",
            "Mean_SHAP_MCI",
            "Mean_SHAP_AD"
        ]
    ]
    .head(10)
    .to_string(index=False)
)

Plotting 5a: Global SHAP per class...
Number of features: 26
Type of shap_values: <class 'numpy.ndarray'>
SHAP array shape: (150, 26, 3)
CN standardized shape: (150, 26)
MCI standardized shape: (150, 26)
AD standardized shape: (150, 26)
Stacked class importance shape: (3, 26)
Number of feature names: 26
Number of overall SHAP values: 26

✅ Figure: ADNI results/figures/E5a_shap_global.png
✅ Importance table: ADNI results/E5_shap_importance_global.csv

Top 10 features across all classes:
        Feature  Mean_SHAP  Mean_SHAP_CN  Mean_SHAP_MCI  Mean_SHAP_AD
   FAQ_FAQTOTAL   0.105619      0.111146       0.078715      0.126997
   ADAS_TOTAL13   0.049212      0.059710       0.037038      0.050888
      MOCA_MOCA   0.049135      0.069376       0.046086      0.031944
   MMSE_MMSCORE   0.045670      0.054181       0.033398      0.049430
  ADAS_TOTSCORE   0.024598      0.028374       0.016338      0.029081
UCSFFSX7_ST29SV   0.013730      0.015626       0.009385      0.016179
            AGE   0.008227      0.010870       0.009387      0.004425
UCSFFSX7_ST30SV   0.007800      0.009785       0.005752      0.007865
UCSFFSX7_ST12SV   0.007098      0.007927       0.003841      0.009525
 UPENNBIOMK_TAU   0.004695      0.005231       0.003303      0.005553

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# ── Plot 5a-Summary: Global SHAP (Mean Across All Classes) ────────
plt.figure(figsize=(10, 6))

# Get top 10 features from the imp_df created in the previous cell
top_10_global = imp_df.head(10).copy()
top_10_global['Display_Name'] = top_10_global['Feature'].map(lambda x: FEATURE_LABELS.get(x, x))

sns.barplot(
    data=top_10_global,
    x='Mean_SHAP',
    y='Display_Name',
    palette='viridis',
    hue='Display_Name',
    legend=False
)

plt.title('FRAME-AD: Top 10 Global Biomarkers\n(Mean Absolute SHAP Value across CN, MCI, and AD)', fontweight='bold')
plt.xlabel('Mean |SHAP Value|')
plt.ylabel('Feature')
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()

plt.savefig(f"{OUTPUT_DIR}/figures/E5a_shap_global_summary.png", dpi=150)
plt.show()

print(f"\n✅ Summary Figure saved: {OUTPUT_DIR}/figures/E5a_shap_global_summary.png")

✅ Summary Figure saved: ADNI results/figures/E5a_shap_global_summary.png

## Experiment 5b: Combinatorial SHAP Feature Ablation

In [ ]:
# Extract top 5 features for use in E5b
TOP_5_SHAP_FEATURES = imp_df["Feature"].head(5).tolist()
print("\nTop 5 SHAP features for E5b:", TOP_5_SHAP_FEATURES)

Top 5 SHAP features for E5b: ['FAQ_FAQTOTAL', 'ADAS_TOTAL13', 'MOCA_MOCA', 'MMSE_MMSCORE', 'ADAS_TOTSCORE']

In [ ]:
import os
import gc
import numpy as np
import pandas as pd
import itertools

print('=' * 70)
print('EXPERIMENT 5b: COMBINATORIAL SHAP FEATURE ABLATION')
print('=' * 70)

# TOP_5_SHAP_FEATURES is set automatically at the end of E5a
# Make sure E5a has been run before this cell

# --- Baseline: all 5 SHAP features ---
print("Calculating baseline using all 5 SHAP features...")
full_set_summary = evaluate_tabpfn_subset(TOP_5_SHAP_FEATURES)
baseline_auc = full_set_summary['AUC_Macro_Mean']
baseline_f1  = full_set_summary['F1_Macro_Mean']
baseline_acc = full_set_summary['Accuracy_Mean']
print(f"Baseline: AUC={baseline_auc:.4f}, F1={baseline_f1:.4f}, Acc={baseline_acc:.4f}")


# --- Perform Combinatorial Ablation ---
e5_6_results = []

# Loop through all non-empty subsets of the top 5 features (31 total)
for r in range(1, len(TOP_5_SHAP_FEATURES) + 1):
    for combo in itertools.combinations(TOP_5_SHAP_FEATURES, r):

        current_feature_set = list(combo)
        display_names = [FEATURE_LABELS.get(f, f) for f in current_feature_set]

        print(f"\n  Testing subset ({r} feature{'s' if r > 1 else ''}): {', '.join(display_names)}")

        try:
            summary = evaluate_tabpfn_subset(current_feature_set)

            auc_drop = baseline_auc - summary['AUC_Macro_Mean']
            f1_drop  = baseline_f1  - summary['F1_Macro_Mean']
            acc_drop = baseline_acc - summary['Accuracy_Mean']

            e5_6_results.append({
                'Feature_Subset':           ', '.join(display_names),
                'Features_In_Subset_Count': len(current_feature_set),
                'AUC_Macro_Mean':           summary['AUC_Macro_Mean'],
                'AUC_Macro_SD':             summary['AUC_Macro_SD'],
                'F1_Macro_Mean':            summary['F1_Macro_Mean'],
                'F1_Macro_SD':              summary['F1_Macro_SD'],
                'Accuracy_Mean':            summary['Accuracy_Mean'],
                'Accuracy_SD':              summary['Accuracy_SD'],
                'Performance_Drop_AUC':     auc_drop,
                'Performance_Drop_F1':      f1_drop,
                'Performance_Drop_Acc':     acc_drop
            })

            print(
                f"    AUC={summary['AUC_Macro_Mean']:.4f} (Drop={auc_drop:.4f}), "
                f"F1={summary['F1_Macro_Mean']:.4f} (Drop={f1_drop:.4f}), "
                f"Acc={summary['Accuracy_Mean']:.4f} (Drop={acc_drop:.4f})"
            )

        except Exception as e:
            print(f"  Error on subset {display_names}: {e}")


# Convert results to DataFrame
e5_6_df = pd.DataFrame(e5_6_results)
os.makedirs(OUTPUT_DIR, exist_ok=True)
e5_6_df.to_csv(f'{OUTPUT_DIR}/E5_6_combinatorial_shap_ablation.csv', index=False)

print("\n" + "=" * 70)
print("EXPERIMENT 5b COMPLETE: COMBINATORIAL SHAP FEATURE ABLATION RESULTS")
print("=" * 70)

display(e5_6_df.sort_values(by='Performance_Drop_AUC', ascending=False).round(4))

print(f"\n✅ Results saved to: {OUTPUT_DIR}/E5_6_combinatorial_shap_ablation.csv")

======================================================================
EXPERIMENT 5b: COMBINATORIAL SHAP FEATURE ABLATION
======================================================================
Calculating baseline using all 5 SHAP features...
Baseline: AUC=0.8946, F1=0.7472, Acc=0.7497

  Testing subset (1 feature): FAQ
    AUC=0.8306 (Drop=0.0640), F1=0.6771 (Drop=0.0701), Acc=0.6922 (Drop=0.0576)

  Testing subset (1 feature): ADAS-Cog 13
    AUC=0.8184 (Drop=0.0762), F1=0.6292 (Drop=0.1180), Acc=0.6486 (Drop=0.1011)

  Testing subset (1 feature): MoCA
    AUC=0.6929 (Drop=0.2017), F1=0.4567 (Drop=0.2905), Acc=0.4916 (Drop=0.2581)

  Testing subset (1 feature): MMSE
    AUC=0.7843 (Drop=0.1102), F1=0.6259 (Drop=0.1213), Acc=0.6273 (Drop=0.1224)

  Testing subset (1 feature): ADAS-Cog 11
    AUC=0.8115 (Drop=0.0830), F1=0.6246 (Drop=0.1226), Acc=0.6462 (Drop=0.1035)

  Testing subset (2 features): FAQ, ADAS-Cog 13
    AUC=0.8666 (Drop=0.0280), F1=0.6996 (Drop=0.0476), Acc=0.7105 (Drop=0.0392)

  Testing subset (2 features): FAQ, MoCA
    AUC=0.8581 (Drop=0.0365), F1=0.6941 (Drop=0.0531), Acc=0.7084 (Drop=0.0414)

  Testing subset (2 features): FAQ, MMSE
    AUC=0.8693 (Drop=0.0253), F1=0.7171 (Drop=0.0301), Acc=0.7232 (Drop=0.0265)

  Testing subset (2 features): FAQ, ADAS-Cog 11
    AUC=0.8643 (Drop=0.0303), F1=0.6956 (Drop=0.0516), Acc=0.7076 (Drop=0.0422)

  Testing subset (2 features): ADAS-Cog 13, MoCA
    AUC=0.8364 (Drop=0.0582), F1=0.6599 (Drop=0.0873), Acc=0.6738 (Drop=0.0759)

  Testing subset (2 features): ADAS-Cog 13, MMSE
    AUC=0.8538 (Drop=0.0408), F1=0.6948 (Drop=0.0524), Acc=0.7014 (Drop=0.0484)

  Testing subset (2 features): ADAS-Cog 13, ADAS-Cog 11
    AUC=0.8227 (Drop=0.0719), F1=0.6406 (Drop=0.1066), Acc=0.6576 (Drop=0.0922)

  Testing subset (2 features): MoCA, MMSE
    AUC=0.8257 (Drop=0.0688), F1=0.6519 (Drop=0.0953), Acc=0.6565 (Drop=0.0932)

  Testing subset (2 features): MoCA, ADAS-Cog 11
    AUC=0.8328 (Drop=0.0618), F1=0.6534 (Drop=0.0938), Acc=0.6662 (Drop=0.0835)

  Testing subset (2 features): MMSE, ADAS-Cog 11
    AUC=0.8502 (Drop=0.0444), F1=0.6896 (Drop=0.0576), Acc=0.6968 (Drop=0.0530)

  Testing subset (3 features): FAQ, ADAS-Cog 13, MoCA
    AUC=0.8766 (Drop=0.0180), F1=0.7139 (Drop=0.0333), Acc=0.7238 (Drop=0.0259)

  Testing subset (3 features): FAQ, ADAS-Cog 13, MMSE
    AUC=0.8866 (Drop=0.0080), F1=0.7380 (Drop=0.0092), Acc=0.7400 (Drop=0.0097)

  Testing subset (3 features): FAQ, ADAS-Cog 13, ADAS-Cog 11
    AUC=0.8659 (Drop=0.0286), F1=0.7028 (Drop=0.0444), Acc=0.7127 (Drop=0.0370)

  Testing subset (3 features): FAQ, MoCA, MMSE
    AUC=0.8857 (Drop=0.0088), F1=0.7315 (Drop=0.0157), Acc=0.7343 (Drop=0.0154)

  Testing subset (3 features): FAQ, MoCA, ADAS-Cog 11
    AUC=0.8737 (Drop=0.0208), F1=0.7149 (Drop=0.0323), Acc=0.7238 (Drop=0.0259)

  Testing subset (3 features): FAQ, MMSE, ADAS-Cog 11
    AUC=0.8848 (Drop=0.0097), F1=0.7346 (Drop=0.0126), Acc=0.7381 (Drop=0.0116)

  Testing subset (3 features): ADAS-Cog 13, MoCA, MMSE
    AUC=0.8675 (Drop=0.0270), F1=0.7115 (Drop=0.0357), Acc=0.7141 (Drop=0.0357)

  Testing subset (3 features): ADAS-Cog 13, MoCA, ADAS-Cog 11
    AUC=0.8400 (Drop=0.0546), F1=0.6646 (Drop=0.0826), Acc=0.6773 (Drop=0.0724)

  Testing subset (3 features): ADAS-Cog 13, MMSE, ADAS-Cog 11
    AUC=0.8564 (Drop=0.0382), F1=0.7005 (Drop=0.0467), Acc=0.7051 (Drop=0.0446)

  Testing subset (3 features): MoCA, MMSE, ADAS-Cog 11
    AUC=0.8642 (Drop=0.0304), F1=0.7045 (Drop=0.0427), Acc=0.7068 (Drop=0.0430)

  Testing subset (4 features): FAQ, ADAS-Cog 13, MoCA, MMSE
    AUC=0.8947 (Drop=-0.0002), F1=0.7450 (Drop=0.0022), Acc=0.7468 (Drop=0.0030)

  Testing subset (4 features): FAQ, ADAS-Cog 13, MoCA, ADAS-Cog 11
    AUC=0.8763 (Drop=0.0183), F1=0.7165 (Drop=0.0307), Acc=0.7254 (Drop=0.0243)

  Testing subset (4 features): FAQ, ADAS-Cog 13, MMSE, ADAS-Cog 11
    AUC=0.8868 (Drop=0.0078), F1=0.7379 (Drop=0.0093), Acc=0.7419 (Drop=0.0078)

  Testing subset (4 features): FAQ, MoCA, MMSE, ADAS-Cog 11
    AUC=0.8929 (Drop=0.0017), F1=0.7476 (Drop=-0.0004), Acc=0.7511 (Drop=-0.0014)

  Testing subset (4 features): ADAS-Cog 13, MoCA, MMSE, ADAS-Cog 11
    AUC=0.8685 (Drop=0.0261), F1=0.7120 (Drop=0.0352), Acc=0.7159 (Drop=0.0338)

  Testing subset (5 features): FAQ, ADAS-Cog 13, MoCA, MMSE, ADAS-Cog 11
    AUC=0.8946 (Drop=0.0000), F1=0.7472 (Drop=0.0000), Acc=0.7497 (Drop=0.0000)

======================================================================
EXPERIMENT 5b COMPLETE: COMBINATORIAL SHAP FEATURE ABLATION RESULTS
======================================================================

,Feature_Subset,Features_In_Subset_Count,AUC_Macro_Mean,AUC_Macro_SD,F1_Macro_Mean,F1_Macro_SD,Accuracy_Mean,Accuracy_SD,Performance_Drop_AUC,Performance_Drop_F1,Performance_Drop_Acc
2,MoCA,1,0.6929,0.0094,0.4567,0.0088,0.4916,0.0130,0.2017,0.2905,0.2581
3,MMSE,1,0.7843,0.0084,0.6259,0.0146,0.6273,0.0135,0.1102,0.1213,0.1224
4,ADAS-Cog 11,1,0.8115,0.0092,0.6246,0.0248,0.6462,0.0185,0.0830,0.1226,0.1035
1,ADAS-Cog 13,1,0.8184,0.0100,0.6292,0.0205,0.6486,0.0187,0.0762,0.1180,0.1011
11,"ADAS-Cog 13, ADAS-Cog 11",2,0.8227,0.0087,0.6406,0.0214,0.6576,0.0168,0.0719,0.1066,0.0922
12,"MoCA, MMSE",2,0.8257,0.0069,0.6519,0.0110,0.6565,0.0098,0.0688,0.0953,0.0932
0,FAQ,1,0.8306,0.0072,0.6771,0.0174,0.6922,0.0159,0.0640,0.0701,0.0576
13,"MoCA, ADAS-Cog 11",2,0.8328,0.0088,0.6534,0.0167,0.6662,0.0163,0.0618,0.0938,0.0835
9,"ADAS-Cog 13, MoCA",2,0.8364,0.0117,0.6599,0.0232,0.6738,0.0201,0.0582,0.0873,0.0759
22,"ADAS-Cog 13, MoCA, ADAS-Cog 11",3,0.8400,0.0112,0.6646,0.0203,0.6773,0.0184,0.0546,0.0826,0.0724
14,"MMSE, ADAS-Cog 11",2,0.8502,0.0069,0.6896,0.0192,0.6968,0.0149,0.0444,0.0576,0.0530
10,"ADAS-Cog 13, MMSE",2,0.8538,0.0052,0.6948,0.0165,0.7014,0.0135,0.0408,0.0524,0.0484
23,"ADAS-Cog 13, MMSE, ADAS-Cog 11",3,0.8564,0.0069,0.7005,0.0175,0.7051,0.0149,0.0382,0.0467,0.0446
6,"FAQ, MoCA",2,0.8581,0.0105,0.6941,0.0221,0.7084,0.0184,0.0365,0.0531,0.0414
24,"MoCA, MMSE, ADAS-Cog 11",3,0.8642,0.0074,0.7045,0.0166,0.7068,0.0139,0.0304,0.0427,0.0430
8,"FAQ, ADAS-Cog 11",2,0.8643,0.0085,0.6956,0.0206,0.7076,0.0198,0.0303,0.0516,0.0422
17,"FAQ, ADAS-Cog 13, ADAS-Cog 11",3,0.8659,0.0097,0.7028,0.0190,0.7127,0.0176,0.0286,0.0444,0.0370
5,"FAQ, ADAS-Cog 13",2,0.8666,0.0098,0.6996,0.0137,0.7105,0.0132,0.0280,0.0476,0.0392
21,"ADAS-Cog 13, MoCA, MMSE",3,0.8675,0.0079,0.7115,0.0221,0.7141,0.0201,0.0270,0.0357,0.0357
29,"ADAS-Cog 13, MoCA, MMSE, ADAS-Cog 11",4,0.8685,0.0082,0.7120,0.0247,0.7159,0.0224,0.0261,0.0352,0.0338
7,"FAQ, MMSE",2,0.8693,0.0081,0.7171,0.0130,0.7232,0.0123,0.0253,0.0301,0.0265
19,"FAQ, MoCA, ADAS-Cog 11",3,0.8737,0.0097,0.7149,0.0110,0.7238,0.0107,0.0208,0.0323,0.0259
26,"FAQ, ADAS-Cog 13, MoCA, ADAS-Cog 11",4,0.8763,0.0096,0.7165,0.0117,0.7254,0.0106,0.0183,0.0307,0.0243
15,"FAQ, ADAS-Cog 13, MoCA",3,0.8766,0.0098,0.7139,0.0113,0.7238,0.0096,0.0180,0.0333,0.0259
20,"FAQ, MMSE, ADAS-Cog 11",3,0.8848,0.0071,0.7346,0.0143,0.7381,0.0156,0.0097,0.0126,0.0116
18,"FAQ, MoCA, MMSE",3,0.8857,0.0091,0.7315,0.0103,0.7343,0.0102,0.0088,0.0157,0.0154
16,"FAQ, ADAS-Cog 13, MMSE",3,0.8866,0.0069,0.7380,0.0177,0.7400,0.0159,0.0080,0.0092,0.0097
27,"FAQ, ADAS-Cog 13, MMSE, ADAS-Cog 11",4,0.8868,0.0070,0.7379,0.0123,0.7419,0.0115,0.0078,0.0093,0.0078
28,"FAQ, MoCA, MMSE, ADAS-Cog 11",4,0.8929,0.0086,0.7476,0.0089,0.7511,0.0095,0.0017,-0.0004,-0.0014
30,"FAQ, ADAS-Cog 13, MoCA, MMSE, ADAS-Cog 11",5,0.8946,0.0090,0.7472,0.0145,0.7497,0.0148,0.0000,0.0000,0.0000
25,"FAQ, ADAS-Cog 13, MoCA, MMSE",4,0.8947,0.0089,0.7450,0.0146,0.7468,0.0133,-0.0002,0.0022,0.0030

✅ Results saved to: ADNI results/E5_6_combinatorial_shap_ablation.csv

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

top_n = 5
top_combinations_highest_auc_df = e5_6_df.sort_values(by='AUC_Macro_Mean', ascending=False).head(top_n).copy()

# --- Format Mean ± SD columns ---
metrics_to_format = ['AUC_Macro', 'F1_Macro', 'Accuracy']
for metric_base in metrics_to_format:
    top_combinations_highest_auc_df[metric_base] = top_combinations_highest_auc_df.apply(
        lambda row: f"{row[f'{metric_base}_Mean']:.4f} ± {row[f'{metric_base}_SD']:.4f}",
        axis=1
    )

# --- Select relevant columns ---
csv_output_highest_auc_df = top_combinations_highest_auc_df[[
    'Feature_Subset',
    'Features_In_Subset_Count',
    'AUC_Macro',
    'F1_Macro',
    'Accuracy',
    'Performance_Drop_AUC',
    'Performance_Drop_F1',
    'Performance_Drop_Acc'
]].rename(columns={
    'Feature_Subset':           'Feature Subset',
    'Features_In_Subset_Count': 'Features in Subset',
    'AUC_Macro':                'AUC (Mean ± SD)',
    'F1_Macro':                 'F1-Macro (Mean ± SD)',
    'Accuracy':                 'Accuracy (Mean ± SD)',
    'Performance_Drop_AUC':     'AUC Drop',
    'Performance_Drop_F1':      'F1-Macro Drop',
    'Performance_Drop_Acc':     'Accuracy Drop'
})

# --- Save to CSV ---
csv_filename_highest_auc = f'{OUTPUT_DIR}/E5_6_top{top_n}_combinatorial_ablation_highest_auc_summary.csv'
csv_output_highest_auc_df.to_csv(csv_filename_highest_auc, index=False)
print(f"\n✅ Top {top_n} results saved to: {csv_filename_highest_auc}")

print(f"\nTop {top_n} Combinations by Highest AUC:")
display(csv_output_highest_auc_df)

# --- Bar Chart ---
plt.figure(figsize=(14, 8))
sns.barplot(
    data=top_combinations_highest_auc_df,
    x='Feature_Subset',
    y='AUC_Macro_Mean',
    palette='viridis'
)

plt.title(f'Top {top_n} Combinatorial Ablation Results: Highest AUC Values', fontweight='bold')
plt.xlabel('Feature Subset')
plt.ylabel('AUC Macro Mean')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

plot_filename_highest_auc = f'{OUTPUT_DIR}/figures/E5_6_top{top_n}_combinatorial_ablation_highest_auc.png'
plt.savefig(plot_filename_highest_auc, dpi=300, bbox_inches='tight')
plt.show()

print(f"\n✅ Visualization saved to: {plot_filename_highest_auc}")

✅ Top 5 results saved to: ADNI results/E5_6_top5_combinatorial_ablation_highest_auc_summary.csv

Top 5 Combinations by Highest AUC:

,Feature Subset,Features in Subset,AUC (Mean ± SD),F1-Macro (Mean ± SD),Accuracy (Mean ± SD),AUC Drop,F1-Macro Drop,Accuracy Drop
25,"FAQ, ADAS-Cog 13, MoCA, MMSE",4,0.8947 ± 0.0089,0.7450 ± 0.0146,0.7468 ± 0.0133,-0.000166,0.002211,0.002973
30,"FAQ, ADAS-Cog 13, MoCA, MMSE, ADAS-Cog 11",5,0.8946 ± 0.0090,0.7472 ± 0.0145,0.7497 ± 0.0148,0.000000,0.000000,0.000000
28,"FAQ, MoCA, MMSE, ADAS-Cog 11",4,0.8929 ± 0.0086,0.7476 ± 0.0089,0.7511 ± 0.0095,0.001725,-0.000413,-0.001351
27,"FAQ, ADAS-Cog 13, MMSE, ADAS-Cog 11",4,0.8868 ± 0.0070,0.7379 ± 0.0123,0.7419 ± 0.0115,0.007795,0.009250,0.007838
16,"FAQ, ADAS-Cog 13, MMSE",3,0.8866 ± 0.0069,0.7380 ± 0.0177,0.7400 ± 0.0159,0.007988,0.009156,0.009730

✅ Visualization saved to: ADNI results/figures/E5_6_top5_combinatorial_ablation_highest_auc.png

### 5b — APOE ε4 Subgroup SHAP Analysis

In [ ]:
print("  Plotting 5b: APOE4 subgroup SHAP...")

apoe_col   = 'APOERES_?4 Count'
feat_names = list(Xshap_named.columns)

if apoe_col in Xshap.columns:
    # Non-carriers (0 alleles) vs Carriers (>=1 allele)
    mask_nc = Xshap[apoe_col] == 0
    mask_c  = Xshap[apoe_col] >= 1

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    for ax, mask, label, color in zip(
        axes,
        [mask_nc,   mask_c],
        ['Non-carrier (0 alleles)', 'Carrier (≥1 allele)'],
        ['#028090', '#E11D48']
    ):
        n = mask.sum()
        if n < 5:
            ax.text(0.5, 0.5, f'Insufficient data\n(n={n})',
                    ha='center', va='center', transform=ax.transAxes)
            continue

        sv_sub   = [sv[mask.values] for sv in shap_values]
        mi       = np.mean([np.abs(sv).mean(axis=0) for sv in sv_sub], axis=0)
        order    = np.argsort(mi)[-12:]

        ax.barh([feat_names[i] for i in order], mi[order],
                color=color, alpha=0.85, edgecolor='white')
        ax.set_title(f'APOE ε4 {label}\n(n={n})',
                     fontweight='bold', fontsize=11)
        ax.set_xlabel('Mean |SHAP Value|', fontsize=10)
        ax.grid(axis='x', alpha=0.3)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

    plt.suptitle('FRAME-AD: SHAP Feature Importance by APOE ε4 Status',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f"{OUTPUT_DIR}/figures/E5b_shap_apoe4.png", dpi=150, bbox_inches='tight')
    plt.show()
    print(f"\n✅ Figure: {OUTPUT_DIR}/figures/E5b_shap_apoe4.png")
else:
    print(f"  ⚠️  Column '{apoe_col}' not found in SHAP sample — skipping APOE4 analysis")

  Plotting 5b: APOE4 subgroup SHAP...

✅ Figure: ADNI results/figures/E5b_shap_apoe4.png

### 5c — Sex Subgroup SHAP Analysis

In [ ]:
print("  Plotting 5c: Sex subgroup SHAP...")

sex_col    = 'PTDEMOG_PTGENDER'
feat_names = list(Xshap_named.columns)
sex_map    = {1.0: 'Male', 2.0: 'Female'}
sex_colors = {1.0: '#0D1B40', 2.0: '#028090'}

if sex_col in Xshap.columns:
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    for ax, val in zip(axes, [1.0, 2.0]):
        mask = Xshap[sex_col] == val
        n    = mask.sum()
        label = sex_map.get(val, str(val))

        if n < 5:
            ax.text(0.5, 0.5, f'Insufficient data\n(n={n})',
                    ha='center', va='center', transform=ax.transAxes)
            continue

        sv_sub = [sv[mask.values] for sv in shap_values]
        mi     = np.mean([np.abs(sv).mean(axis=0) for sv in sv_sub], axis=0)
        order  = np.argsort(mi)[-12:]

        ax.barh([feat_names[i] for i in order], mi[order],
                color=sex_colors[val], alpha=0.85, edgecolor='white')
        ax.set_title(f'{label} (n={n})', fontweight='bold', fontsize=11)
        ax.set_xlabel('Mean |SHAP Value|', fontsize=10)
        ax.grid(axis='x', alpha=0.3)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)

    plt.suptitle('FRAME-AD: SHAP Feature Importance by Sex',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(f"{OUTPUT_DIR}/figures/E5c_shap_sex.png", dpi=150, bbox_inches='tight')
    plt.show()
    print(f"\n✅ Figure: {OUTPUT_DIR}/figures/E5c_shap_sex.png")
else:
    print(f"  ⚠️  Column '{sex_col}' not found in SHAP sample — skipping sex analysis")

  Plotting 5c: Sex subgroup SHAP...

✅ Figure: ADNI results/figures/E5c_shap_sex.png

## Section 3.8: Individual-Level Patient Profiling

**From the Methods:**
> *A distinguishing feature of FRAME-AD is its capacity to generate individual-level patient profiles that extend beyond aggregate performance metrics to produce personalized computational representations of each patient's disease state.*

For each patient **i** with feature vector **xᵢ**, FRAME-AD produces:

> **Profile(i) = { P(CN | xᵢ),  P(MCI | xᵢ),  P(AD | xᵢ),  φᵢ }**

where φᵢ is the individual SHAP attribution vector identifying biomarkers driving that patient's prediction.

This cell generates and visualizes individual patient profiles for a representative sample of test patients.

In [ ]:
# ── NOTE ─────────────────────────────────────────────────────
# This cell requires the following variables from earlier cells:
#   clf_shap     — fitted TabPFN model (from E5 SHAP Setup cell)
#   explainer    — fitted KernelExplainer (from E5 SHAP Setup cell)
#   shap_values  — computed SHAP values (from E5 SHAP Setup cell)
#   Xshap        — SHAP test sample (from E5 SHAP Setup cell)
#   yshap        — true labels for SHAP sample
#   FEATURE_LABELS — human-readable feature names
# ─────────────────────────────────────────────────────────────

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

CLASS_NAMES  = {0: 'CN', 1: 'MCI', 2: 'AD'}
CLASS_COLORS = {'CN': '#028090', 'MCI': '#F59E0B', 'AD': '#E11D48'}

# Get predicted probabilities for all SHAP test samples
all_probas = clf_shap.predict_proba(Xshap)   # shape [n_samples, 3]
all_preds  = all_probas.argmax(axis=1)

# ── Build profile dataframe ───────────────────────────────────
profiles = pd.DataFrame({
    'True_Label':    [CLASS_NAMES[y] for y in yshap.values],
    'Pred_Label':    [CLASS_NAMES[p] for p in all_preds],
    'P_CN':          all_probas[:, 0].round(4),
    'P_MCI':         all_probas[:, 1].round(4),
    'P_AD':          all_probas[:, 2].round(4),
    'Correct':       (all_preds == yshap.values),
}, index=Xshap.index)

# Add top biomarker (highest mean |SHAP| across classes)
mean_shap_per_patient = np.mean(
    [np.abs(shap_values[ci]) for ci in range(3)], axis=0
)  # shape [n_samples, n_features]

feat_names    = list(Xshap.rename(columns=FEATURE_LABELS).columns)
top_feat_idx  = mean_shap_per_patient.argmax(axis=1)
profiles['Top_Biomarker'] = [feat_names[i] for i in top_feat_idx]

print(f"✅ Individual profiles generated for {len(profiles)} test patients")
print(f"\nProfile sample (first 10 rows):")
print(profiles.head(10).to_string())
print(f"\nOverall prediction accuracy on SHAP sample: "
      f"{profiles['Correct'].mean()*100:.1f}%")

✅ Individual profiles generated for 150 test patients

Profile sample (first 10 rows):
     True_Label Pred_Label    P_CN   P_MCI    P_AD  Correct  Top_Biomarker
146          AD         AD  0.0003  0.1015  0.8981     True            FAQ
595          AD         AD  0.0000  0.0036  0.9964     True            FAQ
143          AD        MCI  0.1340  0.7962  0.0697    False            FAQ
882         MCI        MCI  0.3491  0.6355  0.0154     True            FAQ
3350         CN         CN  0.5304  0.4333  0.0364     True           MMSE
66           AD         AD  0.0005  0.0756  0.9239     True            FAQ
2090        MCI        MCI  0.2418  0.6422  0.1160     True  Hippocampus R
2884        MCI        MCI  0.3834  0.6085  0.0082     True            FAQ
1571         CN         CN  0.6087  0.3696  0.0217     True           MMSE
1148         AD         AD  0.0001  0.0054  0.9945     True            FAQ

Overall prediction accuracy on SHAP sample: 77.3%

### Step 1 — Generate Individual Patient Profiles

In [ ]:
# Select 3 representative patients:
# 1 correctly classified per diagnostic class (CN, MCI, AD)
selected = []
for true_label in ['CN', 'MCI', 'AD']:
    subset = profiles[
        (profiles['True_Label'] == true_label) &
        (profiles['Correct'] == True)
    ]
    if len(subset) >= 1:
        # Sample exactly 1 per class
        selected.extend(subset.sample(1, random_state=42).index.tolist())

print(f"Selected {len(selected)} representative patients for profiling")

# ── Plot: probability bar + SHAP waterfall per patient ────────
# Adjusted figure height for 3 patients
fig = plt.figure(figsize=(20, len(selected) * 4.5))
gs  = gridspec.GridSpec(len(selected), 2, figure=fig,
                        hspace=0.5, wspace=0.35)

for row_idx, pat_idx in enumerate(selected):
    loc       = profiles.index.get_loc(pat_idx)
    true_lbl  = profiles.loc[pat_idx, 'True_Label']
    pred_lbl  = profiles.loc[pat_idx, 'Pred_Label']
    p_cn      = profiles.loc[pat_idx, 'P_CN']
    p_mci     = profiles.loc[pat_idx, 'P_MCI']
    p_ad      = profiles.loc[pat_idx, 'P_AD']
    correct   = profiles.loc[pat_idx, 'Correct']
    status    = '✓ Correct' if correct else '✗ Incorrect'

    # ── LEFT: Probability distribution ──────────────────────
    ax_prob = fig.add_subplot(gs[row_idx, 0])
    classes = ['CN', 'MCI', 'AD']
    probs   = [p_cn, p_mci, p_ad]
    bar_colors = [CLASS_COLORS[c] for c in classes]
    bars = ax_prob.bar(classes, probs, color=bar_colors, alpha=0.85,
                       edgecolor='white', width=0.6)

    # Highlight predicted class
    pred_idx = classes.index(pred_lbl)
    bars[pred_idx].set_edgecolor('black')
    bars[pred_idx].set_linewidth(2)

    # Add probability labels on bars
    for bar, prob in zip(bars, probs):
        ax_prob.text(bar.get_x() + bar.get_width()/2,
                     bar.get_height() + 0.01,
                     f'{prob:.2f}', ha='center', va='bottom',
                     fontsize=9, fontweight='bold')

    ax_prob.set_ylim(0, 1.12)
    ax_prob.set_ylabel('Posterior Probability', fontsize=9)
    ax_prob.set_title(
        f'Patient {row_idx+1}  |  True: {true_lbl}  →  Pred: {pred_lbl}  [{status}]',
        fontsize=10, fontweight='bold',
        color='#028090' if correct else '#E11D48'
    )
    ax_prob.axhline(0.5, color='gray', linestyle='--', alpha=0.4, linewidth=0.8)
    ax_prob.grid(axis='y', alpha=0.2)
    ax_prob.spines['top'].set_visible(False)
    ax_prob.spines['right'].set_visible(False)

    # ── RIGHT: Top SHAP features (waterfall style) ───────────
    ax_shap = fig.add_subplot(gs[row_idx, 1])

    # Average SHAP across classes for this patient
    sv_patient = np.mean(
        [shap_values[ci][loc] for ci in range(3)], axis=0
    )
    feat_names_display = list(Xshap.rename(columns=FEATURE_LABELS).columns)

    # Top 8 features by absolute SHAP
    top_n   = 8
    abs_sv  = np.abs(sv_patient)
    top_idx = np.argsort(abs_sv)[-top_n:]
    sv_top  = sv_patient[top_idx]
    fn_top  = [feat_names_display[i] for i in top_idx]

    bar_cols = ['#E11D48' if v > 0 else '#028090' for v in sv_top]
    ax_shap.barh(fn_top, sv_top, color=bar_cols, alpha=0.82, edgecolor='white')
    ax_shap.axvline(0, color='black', linewidth=0.8)
    ax_shap.set_xlabel('SHAP Value (mean across classes)', fontsize=9)
    ax_shap.set_title(f'Top {top_n} Biomarker Contributions',
                      fontsize=10, fontweight='bold')
    ax_shap.grid(axis='x', alpha=0.2)
    ax_shap.spines['top'].set_visible(False)
    ax_shap.spines['right'].set_visible(False)

plt.suptitle(
    'FRAME-AD: Individual-Level Patient Profiles (3-Patient Subset)\n'
    'Left: Posterior Disease State Probabilities  |  '
    'Right: Biomarker SHAP Contributions',
    fontsize=13, fontweight='bold', y=1.01
)
plt.savefig(f"{OUTPUT_DIR}/figures/S38_individual_profiles_3pt.png",
            dpi=150, bbox_inches='tight')
plt.show()
print(f"\n✅ Figure saved: {OUTPUT_DIR}/figures/S38_individual_profiles_3pt.png")

Selected 3 representative patients for profiling

✅ Figure saved: ADNI results/figures/S38_individual_profiles_3pt.png

### Step 2 — Visualise Representative Patient Profiles

In [ ]:
# ── Save full profile table ────────────────────────────────────
profiles.to_csv(f"{OUTPUT_DIR}/S38_individual_profiles.csv")

# ── Save per-patient SHAP matrix ──────────────────────────────
# Average SHAP across classes for each patient
mean_shap_matrix = np.mean(
    [np.abs(shap_values[ci]) for ci in range(3)], axis=0
)
shap_profile_df = pd.DataFrame(
    mean_shap_matrix,
    columns=Xshap.columns,
    index=Xshap.index
).rename(columns=FEATURE_LABELS)

shap_profile_df.insert(0, 'True_Label',  profiles['True_Label'])
shap_profile_df.insert(1, 'Pred_Label',  profiles['Pred_Label'])
shap_profile_df.insert(2, 'P_CN',        profiles['P_CN'])
shap_profile_df.insert(3, 'P_MCI',       profiles['P_MCI'])
shap_profile_df.insert(4, 'P_AD',        profiles['P_AD'])
shap_profile_df.insert(5, 'Top_Biomarker', profiles['Top_Biomarker'])

shap_profile_df.to_csv(f"{OUTPUT_DIR}/S38_patient_shap_profiles.csv")

print(f"✅ Saved: {OUTPUT_DIR}/S38_individual_profiles.csv")
print(f"✅ Saved: {OUTPUT_DIR}/S38_patient_shap_profiles.csv")
print(f"\nProfile columns:")
print(list(shap_profile_df.columns[:10]), '... +', len(shap_profile_df.columns)-10, 'more')
print(f"\nSample profile (Patient 1):")
print(shap_profile_df.iloc[0, :8].to_string())

✅ Saved: ADNI results/S38_individual_profiles.csv
✅ Saved: ADNI results/S38_patient_shap_profiles.csv

Profile columns:
['True_Label', 'Pred_Label', 'P_CN', 'P_MCI', 'P_AD', 'Top_Biomarker', 'ADAS-Cog 11', 'ADAS-Cog 13', 'FAQ', 'MMSE'] ... + 22 more

Sample profile (Patient 1):
True_Label             AD
Pred_Label             AD
P_CN               0.0003
P_MCI              0.1015
P_AD               0.8981
Top_Biomarker         FAQ
ADAS-Cog 11      0.024763
ADAS-Cog 13      0.064103

### Step 3 — Save Full Profile Table

In [ ]:
print("=" * 55)
print("SECTION 3.8 — PROFILE SUMMARY STATISTICS")
print("=" * 55)

print(f"\nTotal patients profiled : {len(profiles)}")
print(f"Correctly classified    : {profiles['Correct'].sum()} "
      f"({profiles['Correct'].mean()*100:.1f}%)")

print(f"\nMean posterior probabilities by true diagnosis:")
for true_lbl in ['CN', 'MCI', 'AD']:
    sub = profiles[profiles['True_Label'] == true_lbl]
    print(f"  {true_lbl} (n={len(sub)}): "
          f"P(CN)={sub['P_CN'].mean():.3f}  "
          f"P(MCI)={sub['P_MCI'].mean():.3f}  "
          f"P(AD)={sub['P_AD'].mean():.3f}")

print(f"\nTop 5 most common driving biomarkers:")
print(profiles['Top_Biomarker'].value_counts().head(5).to_string())

print(f"\n✅ Section 3.8 complete")
print(f"   Files saved in: {OUTPUT_DIR}/")

=======================================================
SECTION 3.8 — PROFILE SUMMARY STATISTICS
=======================================================

Total patients profiled : 150
Correctly classified    : 116 (77.3%)

Mean posterior probabilities by true diagnosis:
  CN (n=62): P(CN)=0.737  P(MCI)=0.252  P(AD)=0.011
  MCI (n=42): P(CN)=0.282  P(MCI)=0.500  P(AD)=0.218
  AD (n=46): P(CN)=0.040  P(MCI)=0.184  P(AD)=0.776

Top 5 most common driving biomarkers:
Top_Biomarker
FAQ              100
MoCA              23
MMSE              22
ADAS-Cog 13        4
Hippocampus R      1

✅ Section 3.8 complete
   Files saved in: ADNI results/

### Step 4 — Profile Summary Statistics

In [ ]:
# Select 3 representative patients:
# 1 correctly classified per diagnostic class (CN, MCI, AD)
selected_3pt = []
for true_label in ['CN', 'MCI', 'AD']:
    subset = profiles[
        (profiles['True_Label'] == true_label) &
        (profiles['Correct'] == True)
    ]
    if len(subset) >= 1:
        # Sample exactly 1 per class
        selected_3pt.extend(subset.sample(1, random_state=42).index.tolist())

print(f"Selected {len(selected_3pt)} representative patients for profiling")

# ── Plot: probability bar + SHAP waterfall per patient ────────
# Adjusted figure height for 3 patients
fig = plt.figure(figsize=(20, len(selected_3pt) * 4.5))
gs  = gridspec.GridSpec(len(selected_3pt), 2, figure=fig,
                        hspace=0.5, wspace=0.35)

for row_idx, pat_idx in enumerate(selected_3pt):
    loc       = profiles.index.get_loc(pat_idx)
    true_lbl  = profiles.loc[pat_idx, 'True_Label']
    pred_lbl  = profiles.loc[pat_idx, 'Pred_Label']
    p_cn      = profiles.loc[pat_idx, 'P_CN']
    p_mci     = profiles.loc[pat_idx, 'P_MCI']
    p_ad      = profiles.loc[pat_idx, 'P_AD']
    correct   = profiles.loc[pat_idx, 'Correct']
    status    = '✓ Correct' if correct else '✗ Incorrect'

    # ── LEFT: Probability distribution ──────────────────────
    ax_prob = fig.add_subplot(gs[row_idx, 0])
    classes = ['CN', 'MCI', 'AD']
    probs   = [p_cn, p_mci, p_ad]
    bar_colors = [CLASS_COLORS[c] for c in classes]
    bars = ax_prob.bar(classes, probs, color=bar_colors, alpha=0.85,
                       edgecolor='white', width=0.6)

    # Highlight predicted class
    pred_idx = classes.index(pred_lbl)
    bars[pred_idx].set_edgecolor('black')
    bars[pred_idx].set_linewidth(2)

    # Add probability labels on bars
    for bar, prob in zip(bars, probs):
        ax_prob.text(bar.get_x() + bar.get_width()/2,
                     bar.get_height() + 0.01,
                     f'{prob:.2f}', ha='center', va='bottom',
                     fontsize=9, fontweight='bold')

    ax_prob.set_ylim(0, 1.12)
    ax_prob.set_ylabel('Posterior Probability', fontsize=9)
    ax_prob.set_title(
        f'Patient {row_idx+1}  |  True: {true_lbl}  →  Pred: {pred_lbl}  [{status}]',
        fontsize=10, fontweight='bold',
        color='#028090' if correct else '#E11D48'
    )
    ax_prob.axhline(0.5, color='gray', linestyle='--', alpha=0.4, linewidth=0.8)
    ax_prob.grid(axis='y', alpha=0.2)
    ax_prob.spines['top'].set_visible(False)
    ax_prob.spines['right'].set_visible(False)

    # ── RIGHT: Top SHAP features (waterfall style) ───────────
    ax_shap = fig.add_subplot(gs[row_idx, 1])

    # Average SHAP across classes for this patient
    sv_patient = np.mean(
        [shap_values[ci][loc] for ci in range(3)], axis=0
    )
    feat_names_display = list(Xshap.rename(columns=FEATURE_LABELS).columns)

    # Top 8 features by absolute SHAP
    top_n   = 8
    abs_sv  = np.abs(sv_patient)
    top_idx = np.argsort(abs_sv)[-top_n:]
    sv_top  = sv_patient[top_idx]
    fn_top  = [feat_names_display[i] for i in top_idx]

    bar_cols = ['#E11D48' if v > 0 else '#028090' for v in sv_top]
    ax_shap.barh(fn_top, sv_top, color=bar_cols, alpha=0.82, edgecolor='white')
    ax_shap.axvline(0, color='black', linewidth=0.8)
    ax_shap.set_xlabel('SHAP Value (mean across classes)', fontsize=9)
    ax_shap.set_title(f'Top {top_n} Biomarker Contributions',
                      fontsize=10, fontweight='bold')
    ax_shap.grid(axis='x', alpha=0.2)
    ax_shap.spines['top'].set_visible(False)
    ax_shap.spines['right'].set_visible(False)

plt.suptitle(
    'FRAME-AD: Individual-Level Patient Profiles (3-Patient Subset)\n'
    'Left: Posterior Disease State Probabilities  |  '
    'Right: Biomarker SHAP Contributions',
    fontsize=13, fontweight='bold', y=1.01
)
plt.savefig(f"{OUTPUT_DIR}/figures/S38_individual_profiles_3pt.png",
            dpi=150, bbox_inches='tight')
plt.show()
print(f"\n✅ Figure saved: {OUTPUT_DIR}/figures/S38_individual_profiles_3pt.png")

Selected 3 representative patients for profiling

✅ Figure saved: ADNI results/figures/S38_individual_profiles_3pt.png

In [ ]:
import shutil
import os

# Define the name of the folder to zip and the output filename
folder_to_zip = OUTPUT_DIR # Already defined as 'ADNI results'
output_filename = 'frame_ad_all_results'

if os.path.exists(folder_to_zip):
    shutil.make_archive(output_filename, 'zip', folder_to_zip)
    print(f"✅ Successfully created {output_filename}.zip. You can download it from the file browser.")
else:
    print(f"❌ Error: The folder '{folder_to_zip}' was not found.")

✅ Successfully created frame_ad_all_results.zip. You can download it from the file browser.